import asyncio, pathlib, json, sys
from playwright.async_api import async_playwright
PAGE=sys.argv[1]; FAC=sys.argv[2]; OUT=sys.argv[3]; EXP=json.load(open(sys.argv[4],encoding='utf-8'))
res=[]
def ok(name,cond,extra=''):
    res.append((name,bool(cond))); print(('PASS ' if cond else 'FAIL ')+name+((' · '+str(extra)) if (extra and not cond) else ''))
async def main():
    async with async_playwright() as pw:
        b=await pw.chromium.launch()
        ctx=await b.new_context(viewport={'width':1280,'height':900})
        page=await ctx.new_page()
        errs=[]
        page.on('pageerror',lambda e: errs.append(str(e)))
        page.on('console',lambda m: errs.append('console:'+m.text) if m.type=='error' and 'net::' not in m.text and 'Failed to load resource' not in m.text else None)
        await page.route('**/*', lambda r: r.continue_() if r.request.url.startswith('file:') else r.abort())
        url=pathlib.Path(PAGE).resolve().as_uri()
        await page.goto(url); await page.wait_for_timeout(1200)
        ok('page loads without script errors', not errs, errs[:3])
        ev=page.evaluate
        t=await ev("[...document.querySelectorAll('#mod0 .acc-t')].map(x=>x.textContent.trim().split(' — ')[0]).join('|')")
        ok('Section 1 numbering unchanged', t=='1.1|1.2|1.3|1.3.1|1.3.2|1.3.3|1.3.4', t)
        # Section 3
        await ev("showMod(2,null)"); await page.wait_for_timeout(200)
        order=await ev("""(function(){var a=document.querySelector('#mod2 .acc-b');var pos=function(sel){var e=a.querySelector(sel);return e?[...a.querySelectorAll('*')].indexOf(e):-1;};
          return [pos('.u5-how'),pos('#ocGrid'),pos('#ocProfile'),pos('#ocConf'),pos('details.u5-dim'),pos('#ref16')];})()""")
        ok('3.1 order: instructions, scores, profile, submit, seven dimensions, reflection', all(x>=0 for x in order) and order==sorted(order), order)
        ok('3.1 has one instruction block and no separate "How the profile is read"', await ev("document.querySelectorAll('#mod2 .u5-how').length")==1 and 'How the profile is read' not in await ev("document.getElementById('mod2').textContent"))
        how=await ev("document.querySelector('#mod2 .u5-how').textContent")
        ok('instruction block carries both sets of points', all(x in how for x in ['1 is strongly low','A score of 4 or 5 is High','three routines','Submit to My Team’s Capstone','level held by most members','A High level is a disposition to manage','Submit to Facilitator']), how[:200])
        ok('seven score rows, each with what the dimension covers', await ev("document.querySelectorAll('#ocGrid .u5-oc-r select').length")==7 and 'Curiosity, creativity, adaptability to new approaches' in await ev("document.getElementById('ocGrid').textContent"))
        ok('seven dimensions with three levels each', await ev("document.querySelectorAll('#mod2 details.u5-dim').length")==7 and await ev("document.querySelectorAll('#mod2 details.u5-dim .u5-lv').length")==21)
        rt=await ev("[...document.querySelectorAll('#mod2 details.u5-dim .u5-rt li')].map(x=>x.textContent)")
        ok('every routine has its meaning (63)', len(rt)==63 and all(len(x.split('. ',1))==2 and len(x.split('. ',1)[1])>25 for x in rt) and rt[0]=='Clarity Trial. The team agrees to act when it is about 70% sure, and reviews the result afterwards.', rt[:2])
        await page.click('#ocConfBtn'); await page.wait_for_timeout(300)
        ok('submit needs all seven scores', 'Score all seven dimensions' in await ev("document.getElementById('ocMsg').textContent"))
        for j,v in enumerate([5,4,2,3,4,3,1]): await page.select_option('#oc_s_%d'%j, str(v))
        await page.wait_for_timeout(1500)
        lv=await ev("[...document.querySelectorAll('#ocProfile .u5-lv')].map(x=>x.querySelector('.u5-lv-n').textContent+':'+x.querySelector('.u5-lv-h').textContent).join('|')")
        pr=await ev("[...document.querySelectorAll('#ocProfile .u5-rt li')].map(x=>x.textContent)")
        ok('own profile shows the routines with their meanings', len(pr)==21 and pr[0].startswith('48-Hour Validation. A new idea waits two days'), pr[:1])
        ok('own levels follow the rule', lv=='Openness:High|Conscientiousness:High|Extraversion:Low|Agreeableness:Balanced|Emotional Stability:High|Values Alignment:Balanced|Learning Orientation:Low', lv)
        st=json.loads(await ev("JSON.stringify(window.__store.u3m1_lens4)"))
        ok('scores saved while working, same keys as before', st.get('__oceavl_work',{}).get('s')==[5,4,2,3,4,3,1] and st.get('oceavl_scores','').startswith('Openness 5 · Conscientiousness 4') and st.get('oceavl_profile','').startswith('Openness: High (score 5)'))
        await page.click('#ocConfBtn'); await page.wait_for_timeout(500)
        st=json.loads(await ev("JSON.stringify(window.__store.u3m1_lens4)"))
        ok('OCEAVL submitted', 'OCEAVL · My Scores' in st.get('confirmed_items',[]) and 'Submitted' in await ev("document.getElementById('ocConf').textContent"))
        # Section 4
        await ev("showMod(3,null)"); await page.wait_for_timeout(200)
        t=await ev("[...document.querySelectorAll('#mod3 .acc-t')].map(x=>x.textContent.trim()).join('|')")
        ok('Section 4 has two parts', t=='4.1 — Leading Change with One Voice|4.2 — Collective Intelligence Across the Leadership Team', t)
        a41=await ev("document.querySelector('#mod3 .acc').textContent")
        ok('4.1 carries the old 4.1 as notes and the four commitments', all(x in a41 for x in ['What one voice creates','With Collective Intelligence','Without Collective Intelligence','One message','One example','One sequence','One owner']))
        ok('4.1 has one reflection (ref15); ref8 has left', await ev("!!document.getElementById('ref15')") and not await ev("!!document.getElementById('ref8')") and await ev("document.querySelectorAll('#mod3 .acc')[0].querySelectorAll('textarea').length")==1)
        a42=await ev("document.querySelectorAll('#mod3 .acc')[1].textContent")
        ok('4.2 explains the two terms and why they are linked', all(x in a42 for x in ['What this part teaches','Converging Zone Contribution','Alignment Hot Zone','Why the two are shown together','How to read a role card']))
        hz=json.loads(await ev("""JSON.stringify([...document.querySelectorAll('#mod3 .rl-detail')].map(d=>{var c=d.querySelectorAll('.rl-col');var p=[...c[1].querySelectorAll('p.u5-hot')].map(x=>x.textContent);
          return {tag:c[1].querySelector('.d-tag').textContent,p:p,left:c[0].querySelectorAll('p').length,leftEnd:c[0].lastElementChild.textContent,rightEnd:c[1].lastElementChild.textContent};}))"""))
        good=len(hz)==10
        for e,hh in zip(EXP,hz):
            want=[e['need'],'Why your role is inclined to it'+e['why'],'What sets it off'+e['trig'],'What you will see and hear'+e['cues'],'What it costs'+e['cost']]
            if 'check fails' in e['cost']: good=False
            if hh['tag']!=e['tag'] or hh['p']!=want or hh['left']!=3 or not hh['leftEnd'].startswith('When your alignment'): good=False; print('  mismatch',e['role'],hh['tag'],hh['left'],hh['leftEnd'][:40]); print('   ',hh['p']); print('   ',want)
        ok('ten role cards: contribution left with its closing line; hot zone right with need, why, trigger, cues, cost', good)
        ok('roles keep their elements', [h['tag'].split(' · ')[0] for h in hz]==['Shift','Transparency','Time','Skill','Tools','Engagement','Fairness','Authority','Autonomy','Stake'])
        # Section 5
        await ev("showMod(4,null)"); await page.wait_for_timeout(300)
        ok('Section 5 is titled Leading with Clarity', await ev("document.querySelector('#mod4 .mod-hero h2').textContent")=='Leading with Clarity' and 'Alignment Toolkit' not in await ev("[...document.querySelectorAll('.mod')].map(m=>m.textContent).join(' ')"))
        ok('two steps: the 3S Check, then ACE-IT', await ev("[...document.querySelectorAll('#mod4 .step-name')].map(x=>x.textContent).join('|')")=='The 3S Check|ACE-IT')
        s5=await ev("['#mod4 .mod-hero','#mod4 .mod-body > .u5-how','#spm','#sp1'].map(q=>document.querySelector(q).textContent).join(' ')")
        ok('Section 5 names only the 3S Check and ACE-IT', 'SCARF' not in s5 and 'STAT' not in s5)
        ok('no watch list, no toolkit of cues and triggers, no 30-day commitment', not await ev("!!document.getElementById('kitMe')") and not await ev("!!document.getElementById('kitTeam')") and not await ev("!!document.getElementById('syn_30day')")
           and 'atch list' not in s5 and 'trigger' not in s5.lower() and 'Behavioural Commitment' not in s5 and await ev("document.querySelectorAll('#mod4 table.u5-kt').length")==0)
        g=await ev("[...document.querySelectorAll('#spm .u5-s5')].map(c=>c.querySelector('.u5-s5-n').textContent+'|'+c.querySelector('.u5-s5-q').textContent+'|'+c.querySelectorAll('textarea').length+'|'+c.querySelector('.u5-s5-g').textContent.slice(0,40)).join(' ## ')")
        ok('Step 1: Shift, Stake and Step, each with the Section 1 guide and one box', g.count('##')==2 and 'Shift|“What is changing?”|1|What it isThe Shift names the practice' in g and 'Stake|“What do we gain if we change' in g and 'Step|“What do I do differently?”|1' in g, g)
        ok('Step 1 guide carries weak, clear and the move', await ev("document.querySelectorAll('#spm .u5-s5-wc').length")==3 and 'From March, agents resolve complaints on the first call.' in await ev("document.getElementById('spm').textContent") and 'Your moveState the Shift as from and to' in await ev("document.getElementById('spm').textContent"))
        lab=await ev("[...document.querySelectorAll('#spm .u5-s5 label')].map(x=>x.textContent).join(' | ')")
        ok('Step 1 asks in Carol’s words', lab=='Your group’s Shift · What is changing? | Your group’s Stake · What will the organisation gain if it changes, and what will it lose if it stays as it is? | Your group’s Step · What must be done differently?', lab)
        ok('Step 1 shows the Unit 3 lists', 'resolve complaints at first contact' in await ev("document.getElementById('u5KissP').innerText") and await ev("!!document.querySelector('#spm #u5KissP')"))
        await page.click('#spm .u5-b.ok'); await page.wait_for_timeout(400)
        ok('the button in Step 1 opens Step 2', await ev("document.getElementById('sp1').classList.contains('active')") and not await ev("document.getElementById('spm').classList.contains('active')"))
        toc=await ev("document.getElementById('u5TeamOc').textContent")
        ok('Step 2 shows the team OCEAVL profile: seven dimensions, levels and counts, no names', await ev("document.querySelectorAll('#u5TeamOc .u5-lv').length")==7 and 'OpennessHighHigh 3 · Balanced 1 · Low 1' in toc and 'ExtraversionLowHigh 1 · Balanced 1 · Low 3' in toc and 'Emotional StabilityBalanced' in toc and '5 members submitted' in toc, toc[:200])
        a=await ev("[...document.querySelectorAll('#sp1 .u5-s5')].map(c=>c.querySelector('.u5-s5-n').textContent+':'+c.querySelectorAll('textarea').length+':'+[...c.querySelectorAll('.u5-s5-g b')].map(b=>b.textContent).join('/')).join(' | ')")
        ok('Step 2: five ACE-IT behaviours, each with the Section 1 guide and one box', a==' | '.join(n+':1:Definition/What it does for a new practice/Observable' for n in ['Accountability','Commitment','Engagement','Integrity','Transparency']), a)
        ok('Step 2 guide is the lesson text', 'One named person owns the practice and its result.' in await ev("document.getElementById('sp1').textContent") and 'Taking full ownership for results.' in await ev("document.getElementById('sp1').textContent"))
        await page.click('#kitConfBtn'); await page.wait_for_timeout(300)
        msg=await ev("document.getElementById('kitMsg').textContent")
        ok('confirm needs all eight boxes', msg=='Before you confirm, complete: Shift, Stake, Step, Accountability, Commitment, Engagement, Integrity, Transparency.', msg)
        await page.click('#mod4 .step-tab >> nth=0'); await page.wait_for_timeout(200)
        await page.fill('#s5_shift','From March, agents resolve complaints on the first call.'); await page.fill('#s5_stake','We keep the customers who now leave after a two-day wait.'); await page.fill('#s5_step','Agents decide on the call, within their limit.')
        await page.click('#mod4 .step-tab >> nth=1'); await page.wait_for_timeout(200)
        for k in ['accountability','commitment','engagement','integrity']: await page.fill('#s5_'+k,'Expected behaviour for '+k+'.')
        await page.wait_for_timeout(1500)
        st=json.loads(await ev("JSON.stringify(window.__store.u3m1_lens4)"))
        ok('answers save as the group types', st.get('__align_work',{}).get('shift','').startswith('From March') and 'Stake: We keep the customers' in st.get('kit_team','') and 'kit_mind' not in st, list(st.keys()))
        await page.click('#kitConfBtn'); await page.wait_for_timeout(300)
        ok('confirm names the one box still open', await ev("document.getElementById('kitMsg').textContent")=='Before you confirm, complete: Transparency.')
        await page.fill('#s5_transparency','Progress and setbacks are shown to everyone the change affects.'); await page.wait_for_timeout(500)
        await page.click('#kitConfBtn'); await page.wait_for_timeout(700)
        st=json.loads(await ev("JSON.stringify(window.__store.u3m1_lens4)"))
        ok('record confirmed: 3S into kit_mind, ACE-IT into kit_habit, two capstone names', 'Alignment Plan · Mind' in st.get('confirmed_items',[]) and 'Alignment Plan · Habit' in st.get('confirmed_items',[])
           and st.get('kit_mind','').startswith('Shift: From March, agents resolve complaints on the first call.\n\nStake: ') and st.get('kit_mind','').endswith('Step: Agents decide on the call, within their limit.')
           and st.get('kit_habit','').startswith('Accountability: Expected behaviour for accountability.') and st.get('kit_habit','').endswith('Transparency: Progress and setbacks are shown to everyone the change affects.')
           and not any(k in st for k in ['kit_heart','kit_hands','kit_me','__kit_me','__kit_team','syn_30day']), list(st.keys()))
        ok('OCEAVL submission kept beside the record', 'OCEAVL · My Scores' in st.get('confirmed_items',[]) and 'Confirmed' in await ev("document.getElementById('kitOutP').innerText"))
        await page.click('#mod4 .step-tab >> nth=0'); await page.wait_for_timeout(200); await page.fill('#s5_step','Changed.'); await page.wait_for_timeout(1500)
        st=json.loads(await ev("JSON.stringify(window.__store.u3m1_lens4)"))
        ok('an edit removes the record confirmation only', not any(x.startswith('Alignment Plan') for x in st.get('confirmed_items',[])) and 'OCEAVL · My Scores' in st.get('confirmed_items',[]))
        await page.click('#mod4 .step-tab >> nth=1'); await page.wait_for_timeout(200); await page.click('#kitConfBtn'); await page.wait_for_timeout(1500); await page.goto(url); await page.wait_for_timeout(1300)
        ok('after reload: scores and record are back',
           await ev("document.getElementById('oc_s_2').value")=='2' and await ev("document.getElementById('s5_step').value")=='Changed.' and (await ev("document.getElementById('s5_transparency').value")).startswith('Progress and setbacks')
           and 'Confirmed' in await ev("document.getElementById('kitOutP').innerText") and 'Submitted' in await ev("document.getElementById('ocConf').textContent"))
        await ev("window.__teamOc={members:5,submitted:3,dims:null}"); await ev("u5TeamOc(true)"); await page.wait_for_timeout(300)
        ok('team profile waits until every member has submitted', 'Submitted so far: 3 of 5 members.' in await ev("document.getElementById('u5TeamOc').textContent") and await ev("document.querySelectorAll('#u5TeamOc .u5-lv').length")==0)
        await ev("window.__teamOc=null"); await ev("S2R._client.rpc=function(){return Promise.resolve({data:null,error:{message:'x'}});}"); await ev("u5TeamOc(true)"); await page.wait_for_timeout(300)
        ok('team profile falls back to the Capstone when it cannot be read', 'Read it in your team’s Capstone Blueprint' in await ev("document.getElementById('u5TeamOc').textContent"))
        await page.goto(url); await page.wait_for_timeout(1300)
        sm=await ev("document.getElementById('summaryP').textContent")
        ok('summary: five blocks; block 4 leads with one voice; block 5 on the 3S Check and ACE-IT', await ev("document.querySelectorAll('#summaryP .sum-block').length")==5 and 'the CEO at Shift' in sm and 'With the 3S Check you stated the Shift' in sm and 'watch list' not in sm and 'trigger' not in sm.split('What You Applied')[-1] and sm.index('one voice')<sm.index('Converging Zone Contribution'))
        ok('no script errors at the end', not errs, errs[:3])
        # pictures
        await ev("showMod(2,null)"); await ev("document.querySelectorAll('#mod2 .acc').forEach(a=>a.classList.add('open'))"); await page.wait_for_timeout(300)
        await page.screenshot(path=OUT+'/p_s3.png', full_page=True)
        await ev("showMod(3,null)"); await ev("document.querySelectorAll('#mod3 .acc').forEach(a=>a.classList.add('open'))"); await page.click('.rl-card >> nth=0'); await page.wait_for_timeout(300); await page.screenshot(path=OUT+'/p_s4.png', full_page=True)
        await page.click('.rl-card >> nth=6'); await page.wait_for_timeout(300); await (await page.query_selector('#rl6')).screenshot(path=OUT+'/p_s4_cco.png')
        await ev("showMod(4,null)"); await page.click('#mod4 .step-tab >> nth=0'); await page.wait_for_timeout(200); await page.screenshot(path=OUT+'/p_s5_1.png', full_page=True)
        await page.click('#mod4 .step-tab >> nth=1'); await page.wait_for_timeout(600); await page.screenshot(path=OUT+'/p_s5_2.png', full_page=True)
        # phone width
        ph=await b.new_context(viewport={'width':390,'height':800}); pp=await ph.new_page()
        await pp.route('**/*', lambda r: r.continue_() if r.request.url.startswith('file:') else r.abort())
        await pp.goto(url); await pp.wait_for_timeout(1000)
        ws=[]
        for n in range(5):
            await pp.evaluate("showMod(%d,null)"%n); await pp.evaluate("document.querySelectorAll('.mod.active .acc').forEach(a=>a.classList.add('open'))"); await pp.wait_for_timeout(200)
            if n==3: await pp.evaluate("document.querySelector('.rl-card').click()")
            ws.append(await pp.evaluate("document.documentElement.scrollWidth"))
        ok('phone width: no wider than the live page (453, 460, 453, 453, 541)', all(w<=x for w,x in zip(ws,[453,460,453,453,541])), ws)
        await pp.evaluate("showMod(2,null)"); await pp.screenshot(path=OUT+'/p_phone_s3.png', full_page=True)
        await pp.evaluate("showMod(3,null)"); await pp.screenshot(path=OUT+'/p_phone_s4.png', full_page=True)
        # facilitator
        fp=await ctx.new_page(); ferr=[]
        fp.on('pageerror',lambda e: ferr.append(str(e)))
        await fp.route('**/*', lambda r: r.continue_() if r.request.url.startswith('file:') else r.abort())
        await fp.goto(pathlib.Path(FAC).resolve().as_uri()); await fp.wait_for_timeout(900)
        fe=fp.evaluate
        ok('facilitator page loads', not ferr, ferr[:2])
        ok('facilitator: no entry boxes', await fe("document.querySelectorAll('textarea,input,select').length")==0)
        t=await fe("[...document.querySelectorAll('.mod-panel .acc-t')].map(x=>x.textContent.trim().split(' — ')[0]).filter(x=>/^\\d/.test(x)).join('|')")
        ok('facilitator: numbering mirrors the participant page', t=='1.1|1.2|1.3|1.3.1|1.3.2|1.3.3|1.3.4|2.1|2.2|2.3|3.1|4.1|4.2', t)
        f3=await fe("document.getElementById('mod3').textContent")
        ok('facilitator 3.1: activity note before the seven dimensions', f3.index('They score first and read the seven dimensions afterwards')<f3.index('Curiosity, creativity, adaptability') and 'How the profile is read' not in f3)
        f4=await fe("document.getElementById('mod4').textContent")
        ok('facilitator Section 4: one voice first with the notes, then the role cards in plain words', f4.index('4.1 — Leading Change with One Voice')<f4.index('What one voice creates')<f4.index('One message')<f4.index('4.2 — Collective Intelligence')<f4.index('What this part teaches') and 'Section 4.3' not in f4 and 'Why the role is inclined to it' in f4)
        fh=json.loads(await fe("JSON.stringify([...document.querySelectorAll('#mod4 .rl-detail')].map(d=>[d.querySelector('.d-tag').textContent,[...d.querySelectorAll('.rl-col')[1].querySelectorAll('p.u5-hot')].map(x=>x.textContent)]))"))
        ok('facilitator: ten role cards with the same elements, triggers, cues and costs', len(fh)==10 and all(x[0]==e['tag'] and x[1][0]==e['need'] and x[1][2]=='What sets it off'+e['trig'] and x[1][3]=='What is seen and heard'+e['cues'] and x[1][4]=='What it costs'+e['cost'] for x,e in zip(fh,EXP)))
        ok('facilitator 3.1: every routine has its meaning', await fe("document.querySelectorAll('#mod3 details.u5-dim .u5-rt li').length")==63)
        ok('facilitator: Section 5 is titled Leading with Clarity', await fe("document.querySelector('#mod5 .mod-hero h2').textContent")=='Leading with Clarity' and 'Alignment Toolkit' not in await fe("[...document.querySelectorAll('.mod-panel')].map(m=>m.textContent).join(' ')"))
        f5=await fe("['#mod5 .mod-hero','#mod5 .mod-body > .u5-how','#mod5 .mod-body > .fac-note-full','#spm','#sp1'].map(q=>document.querySelector(q).textContent).join(' ')")
        ok('facilitator Section 5: two steps, the same guides, activity notes, no toolkit of cues and triggers', await fe("[...document.querySelectorAll('#mod5 .step-name')].map(x=>x.textContent).join('|')")=='The 3S Check|ACE-IT'
           and await fe("document.querySelectorAll('#spm .u5-s5').length")==3 and await fe("document.querySelectorAll('#sp1 .u5-s5').length")==5 and await fe("document.querySelectorAll('#mod5 .u5-activity').length")==2
           and 'SCARF' not in f5 and 'STAT' not in f5 and 'trigger' not in f5.lower() and 'atch list' not in f5 and 'Behavioural Commitment' not in f5 and 'team OCEAVL profile' in f5 and "Leader’s move" in f5)
        await fe("showMod(3)"); await fe("document.querySelectorAll('#mod3 .acc').forEach(a=>a.classList.add('open'))"); await fp.wait_for_timeout(200); await fp.screenshot(path=OUT+'/f_s3.png', full_page=True)
        await fe("showMod(4)"); await fe("document.querySelectorAll('#mod4 .acc').forEach(a=>a.classList.add('open'))"); await fp.click('#mod4 .rl-card >> nth=0'); await fp.wait_for_timeout(200); await fp.screenshot(path=OUT+'/f_s4.png', full_page=True)
        await fe("showMod(5)"); await fp.wait_for_timeout(200); await fp.screenshot(path=OUT+'/f_s5_1.png', full_page=True)
        await b.close()
    bad=[n for n,c in res if not c]; print('\n%d checks · %d failed'%(len(res),len(bad)), bad)
asyncio.run(main())
