// Unit 1 · Behavioural Strategy Fundamentals — facilitator deck with detailed presenter notes.
// Source: unit1_P.html and unit1_F.html (portal root). Bias and executive-role data are read from unit1_F.html at build time.
// Run: node unit01.js "<output.pptx>" [path-to-logo.png] [path-to-unit1_F.html]
const { Deck, C, F, T, box, badge } = require('./lib2');
const path = require('path');
const fs = require('fs');
const OUT = process.argv[2];
const LOGO = process.argv[3] || path.join(__dirname, '..', '..', 'logo.png');
const UNIT_F = process.argv[4] || path.join(__dirname, '..', '..', 'unit1_F.html');

const N = (...parts) => parts.filter(p => p !== null && p !== undefined && p !== '').join('\n\n');
const dec = s => s.replace(/&amp;/g, '&').replace(/&#39;/g, "'").replace(/&quot;/g, '"');

// ── Data from the facilitator file
const raw = fs.readFileSync(UNIT_F, 'utf8');
const BIASES = JSON.parse(dec(raw.match(/var BIASES=(\{[\s\S]*?\});\s*var CXO=/)[1]));
const CXO = JSON.parse(dec(raw.match(/var CXO=(\{[\s\S]*?\});/)[1]));
const biasNotes = key => BIASES[key].map(b =>
  `${b.name}: ${b.desc}\n  Strategic impact: ${b.impact.join('; ')}.\n  Warning signs: ${b.signal.join('; ')}.`).join('\n\n');
const ROLE_TITLES = { CEO: 'Managing Director', CFO: 'Finance Director', COO: 'Operations Director', CHRO: 'HR Director', CTO: 'IT Director', CMO: 'Marketing Director', CCO: 'Commercial Director', CPO: 'Procurement Director', CRO: 'Risk Director', CSO: 'Strategy Director' };
const cxoNotes = Object.keys(CXO).map(k => `- ${k} (${ROLE_TITLES[k]}): ${CXO[k].t} · Success: ${CXO[k].s}`).join('\n');

(async () => {
  const d = new Deck({ unit: 1, module: 1, moduleName: 'Foundation', title: 'Behavioural Strategy Fundamentals' });

  // 1 ── Cover
  await d.cover({ logo: LOGO, subtitle: 'How judgement, bias and emotional climate shape the strategies organisations pursue',
    notes: N(
      'UNIT 1 · BEHAVIOURAL STRATEGY FUNDAMENTALS\nModule 1 · Foundation · Unit 1 · Unscored',
      'Unit intent (Facilitator Guide):\nUnit 1 establishes the behavioural foundation for the whole programme. Leaders examine how judgement, bias and emotional climate shape the strategies their organisations choose, and practise recognising these forces in their own leadership team. Every later unit relies on the shared vocabulary built here.\nUnit 1 is unscored. Use it to build candour: participants must be willing to name their own biases before they can challenge the team’s. The ground rules set in Orientation carry through all twelve units.',
      'How participants see this unit (participant file):\nThis unit builds your understanding of how human thinking shapes the strategies organisations pursue. You will develop a practical method for identifying cognitive bias in strategy processes, understanding the emotional climate of leadership environments, and contributing to more rigorous, debiased collective decision-making. Your reflections throughout this unit form your Unit 1 portfolio artefact.',
      'Time: section timings in the files add up to 180–245 minutes (about 3 to 4 hours), plus breaks.') });

  // 2 ── Key learning outcomes
  await d.list({ title: 'Key learning outcomes', fontSize: 26, rows: [
    { icon: 'FaCheck', text: 'Critically examine the influence of human judgement and organisational dynamics on strategic decision-making.' },
    { icon: 'FaCheck', text: 'Recognise the behavioural conditions that strengthen or weaken objectivity, decision quality and organisational performance.' },
    { icon: 'FaCheck', text: 'Interpret strategic issues from an integrated enterprise perspective.' }],
    notes: N(
      'KEY LEARNING OUTCOMES (identical in the participant and facilitator files)',
      '1. Critically examine the influence of human judgement and organisational dynamics on strategic decision-making.\n2. Recognise the behavioural conditions that strengthen or weaken objectivity, decision quality and organisational performance.\n3. Interpret strategic issues from an integrated enterprise perspective.',
      'Each section slide carries that section’s two learning outcomes.') });

  // 3 ── Unit journey + Facilitator Guide
  await d.list({ title: 'The unit journey', fontSize: 28, rows: [
    { icon: 'FaCompass', gold: true, label: 'Section 1 · Orientation', text: '— Overview' },
    { icon: 'FaEye', label: 'Section 2 · Awareness', text: '— What' },
    { icon: 'FaLightbulb', label: 'Section 3 · Intelligence', text: '— Why' },
    { icon: 'FaMapMarkedAlt', label: 'Section 4 · Extrapolating', text: '— Where' },
    { icon: 'FaUsers', label: 'Section 5 · Integration', text: '— Collective' },
    { icon: 'FaClipboardCheck', label: 'Section 6 · Application', text: '— In Practice' }],
    notes: N(
      'FACILITATOR GUIDE · SESSION OVERVIEW',
      'Time by section (from the files):\n- Section 1 · Orientation — Overview: 10–15 minutes\n- Section 2 · Awareness — What: 40–55 minutes\n- Section 3 · Intelligence — Why: 25–35 minutes\n- Section 4 · Extrapolating — Where: 35–45 minutes\n- Section 5 · Integration — Collective: 30–40 minutes\n- Section 6 · Application — In Practice: 40–55 minutes',
      'Key Facilitation Questions (use across the unit):\n- “Think of the last major strategic decision in your organisation. Which bias shaped it most, and who in the room noticed?”\n- “What emotional climate does your leadership team bring into strategy conversations? How does it change the decisions you make?”\n- “Which executive role in your team is most often treated as the voice of reality? What does that cost the quality of the decision?”\n- “What one practice would make your next strategy session measurably less biased?”',
      'Watch for: bias spotted only in others. Redirect: “Where did that bias show up in your own last decision?”',
      'Watch for: bias treated as a personal flaw. Frame bias as a predictable feature of human judgement that process design can manage.',
      'Orientation: agree the ground rules for candour and confidentiality before Section 2. The quality of the conversation in every later unit depends on them.') });

  // ── Section 1
  await d.section({ num: 1, name: 'Orientation', anchor: 'Overview', heading: 'Your starting point in the S2R® journey',
    outcomes: ['Recognise how human judgement shapes the way their team debates, decides and sets organisational direction.', 'Articulate a personal learning intention anchored in a current leadership or strategic challenge.'],
    notes: N(
      'SECTION 1 · ORIENTATION — OVERVIEW\nTime: 10–15 minutes including the opening provocation.',
      'Section learning outcomes:\n1. Recognise how human judgement shapes the way their team debates, decides and sets organisational direction.\n2. Articulate a personal learning intention anchored in a current leadership or strategic challenge.',
      'Purpose: This is a scene-setting section. Do not rush it. The quality of engagement throughout the rest of the unit depends on participants understanding why they are here and what they are being asked to do differently.',
      'Content (Understanding the Basics):\nBehavioural Strategy sits at the intersection of cognitive psychology and strategic management.\nBehavioural Strategy, incorporating psychology into strategy recognises that strategy is deeply human. This field bridges cognitive and social insights to improve decision quality. It challenges the assumption that leaders think rationally when charting organisational direction and, more importantly, equips them to do something about it.\nAs you progress through the Strategy2Results® process, you will begin to recognise patterns in how your team debates, how your organisation makes decisions, and how your own mental models shape the strategy your organisation ultimately pursues.',
      'The five sections that follow:\n- AWARENESS: What behavioural strategy is\n- INTELLIGENCE: Why it is critical to strategy management\n- EXTRAPOLATING: Where it fits in the strategy management journey\n- INTEGRATION: How to create collective intelligence from the insights and executive action\n- APPLICATION: How to apply it in practice',
      'Next: the opening question, before any other content.') });
  await d.prompt({ label: 'Opening question', text: 'What is one assumption you hold about how good decisions get made in your organisation?',
    notes: N(
      'OPENING THE SESSION',
      'Ask the group, before showing any content: “What is one assumption you hold about how good decisions get made in your organisation?”',
      'Allow 2–3 responses. Do not challenge or affirm. Simply note them. Return to them at the end of the unit (Unit Summary slide).') });
  await d.prompt({ icon: 'FaPenFancy', label: 'Your learning intention', text: 'What is one thing about your leadership or your organisation’s strategy that you most want to understand differently by the end of this unit?',
    foot: 'Write it in the ✎ Reflection box in Section 1.',
    notes: N(
      'NAVIGATING THE FIVE SECTIONS',
      'Walk participants through the five sections (Awareness · Intelligence · Extrapolating · Integration · Application) displayed on screen. Explain that each section builds on the last — the unit is cumulative. Discourage skipping ahead.',
      'Participant activity (participant file, Section 1, ✎ Reflection): “Before diving in: What brings you here? What is one thing about your leadership or your organisation’s strategy that you most want to understand differently by the end of this unit?” Participants click Save Reflection.',
      'Reflection prompt guidance: Direct participants to the reflection box at the bottom of this section. Ask them to write their intention down. This becomes the anchor for their personal portfolio artefact at the end of Unit 1.',
      'Transition: agree the ground rules for candour and confidentiality before moving to Section 2 (Facilitator Guide).') });

  // ── Section 2
  await d.section({ num: 2, name: 'Awareness', anchor: 'What', heading: 'The foundations — Sections 2.1 to 2.4',
    outcomes: ['Recognise how intuitive thinking, functional expertise and cognitive bias shape strategic judgement.', 'Identify the patterns of bias most active in their own organisation.'],
    notes: N(
      'SECTION 2 · AWARENESS — WHAT\nAwareness — What Behavioural Strategy Is · Sections 2.1 · 2.2 · 2.3 · 2.4\nTime: 40–55 minutes depending on group discussion depth (2.2: 8–10 min · 2.3: 10–12 min · 2.4: 12–15 min).',
      'Section learning outcomes:\n1. Recognise how intuitive thinking, functional expertise and cognitive bias shape strategic judgement.\n2. Identify the patterns of bias most active in their own organisation.',
      'Section intent: This section establishes the conceptual foundation. Participants are introduced to what behavioural strategy is, how individual thinking is structured, how collective thinking breaks down, and what the 20 most common cognitive biases look like in practice. Expect some resistance — experienced leaders often feel they already know this. The role of the facilitator is to make the content feel personally relevant.',
      'Next: the question on the following slide, before moving into Section 2.1.') });
  await d.prompt({ label: 'Before we begin 2.1', text: 'When you make a strategic decision, how much of it do you believe is purely rational?',
    notes: N(
      'BEFORE MOVING INTO SECTION 2.1',
      'Ask the group: “When you make a strategic decision, how much of it do you believe is purely rational?”',
      'Take 2–3 responses. Hold the tension. This prepares the ground for the definition that follows.') });
  {
    const s = d.slide(); d.title(s, '2.1 · Defining behavioural strategy');
    box(s, 0.6, 1.65, 4.3, 5.3, C.tint);
    T(s, 'Traditional strategy asks', { x: 0.9, y: 1.95, w: 3.8, h: 0.5, fontSize: 24, bold: true, color: C.muted });
    T(s, 'What should we do?', { x: 0.9, y: 2.7, w: 3.8, h: 3.5, fontSize: 40, fontFace: F.head, bold: true, color: C.forest, valign: 'middle' });
    box(s, 5.2, 1.65, 7.53, 5.3, C.forest);
    T(s, 'Behavioural strategy asks first', { x: 5.5, y: 1.95, w: 7, h: 0.5, fontSize: 24, bold: true, color: C.gold });
    T(s, 'How does the way we think shape what we believe we should do — and are those thinking patterns helping or hurting us?', { x: 5.5, y: 2.7, w: 7.0, h: 3.9, fontSize: 36, fontFace: F.head, italic: true, color: C.white, valign: 'middle' });
    s.addNotes(N(
      '2.1 · DEFINING BEHAVIOURAL STRATEGY (Foundation Concept)',
      'Key concept to land: The distinction between what we decide and how our thinking shapes what we believe we should decide. This is the unit’s central pivot — everything else builds from it.',
      'Say (read or paraphrase the core question aloud): “How does the way we think shape what we believe we should do — and are those thinking patterns helping or hurting us?” Ask the group to sit with it for a moment before exploring the three concept cards (next slide).',
      'Content:\nBehavioural strategy merges strategic management theory with insights from cognitive and social psychology. Grounded in the work of scholars such as Daniel Kahneman and advanced in the field of behavioural strategy by thinkers like Olivier Sibony, this discipline brings rigour to how decisions are actually made. It acknowledges that strategic choices are the final output of invisible mental filters — shortcuts, ignored data, and trusted patterns — that operate beneath the level of conscious analysis. By identifying these biases, leaders can transition from making decisions based on unexamined belief to making decisions based on rigorous, debiased evaluation.\nWhere traditional strategy asks ‘What should we do?’ — Behavioural strategy asks an equally important prior question: ‘How does the way we think shape what we believe we should do — and are those thinking patterns helping or hurting us?’'));
  }
  await d.cards({ title: '2.1 · Three phrases that carry the idea', cols: 3, items: [
    { icon: 'FaBrain', title: '“The way we think”', text: 'The shortcuts we use, the patterns we trust, the data we unconsciously ignore.' },
    { icon: 'FaBullseye', title: '“What we believe we should do”', text: 'Where those hidden processes surface.' },
    { icon: 'FaBalanceScale', title: '“Helping or hurting us”', text: 'The strategic stakes.' }],
    band: 'If we do not understand how we’re thinking, we can’t evaluate whether our thinking is sound.',
    notes: N(
      '2.1 · THE THREE CARDS AND THE FORMAL DEFINITION',
      'Content (the three cards):\n“The way we think” — Refers to the mental processes running beneath our decisions — the shortcuts we use, the patterns we trust, the data we unconsciously ignore. These processes are largely invisible to us, which is precisely what makes them dangerous in high-stakes contexts.\n“What we believe we should do” — Is where those hidden processes surface. Every strategic recommendation, every resource allocation, every competitive call — each one is filtered through the thinking of the people who made it. The analysis may look objective. The thinking behind it rarely is.\n“Helping or hurting us” — Is the strategic stakes. The same mental shortcuts that make experienced leaders fast and decisive can also make them systematically wrong — overconfident about forecasts, blind to disconfirming signals, or trapped in consensus thinking.\nSo, the question points directly to a practical problem: if we do not understand how we’re thinking, we can’t evaluate whether our thinking is sound.',
      'Participant activity (participant file, Section 2.1): participants click each card and read it.\nAsk: “Which of these three phrases feels most personally relevant to you right now?” Allow brief pair discussion before continuing.',
      'The formal definition (gold quote box): Behavioural Strategy: The application of insights from psychology and behavioural economics to reduce the impact of cognitive biases, emotional distortions, and group dynamics on strategic decisions — enabling leaders to make better choices about direction, resource allocation, and competitive positioning. (Sibony, and others)\nAsk: “Does this definition change how you understood strategy before walking in today?”',
      'Participant reflection (participant file, 2.1, ✎ Reflection): “How does the definition of behavioural strategy apply to your current context? Can you think of a recent decision in your organisation that might have been shaped by invisible mental filters?”') });
  await d.compare({ title: '2.2 · Two systems of thinking', cols: [
    { icon: 'FaBolt', title: 'System 1', sub: 'Fast, automatic, intuitive', points: ['Operates below conscious awareness', 'Produces rapid, confident judgements', 'Vulnerable to cognitive biases'] },
    { icon: 'FaHourglassHalf', title: 'System 2', sub: 'Slow, deliberate, analytical', points: ['Weighs options and trade-offs', 'More reliable for complex problems', 'Requires psychological safety to activate'] }],
    band: 'Know when System 2 is needed, and create the conditions for it to activate.',
    notes: N(
      '2.2 · THE ARCHITECTURE OF HUMAN THINKING IN STRATEGY (Dual-Process Framework)\nTime: 8–10 minutes.',
      'Ask first, before opening the content: “Think of the last major strategic decision your team made. Was the final call driven more by instinct or deliberate analysis?” Take 2–3 responses. This primes the System 1 / System 2 distinction before it appears on screen.',
      'Content:\nTo understand this internal hidden thinking architecture, the dual-process framework developed by Nobel laureate Daniel Kahneman provides a powerful framework for understanding how strategic thinking unfolds in practice.\nKahneman’s dual-process framework reveals that strategic thinking is a dynamic interaction between two internal systems. System 1 provides fast, pattern-based intuition, while System 2 offers the slow effortful analysis required for complexity.\nFor those with a mandate for strategy management, the ability to recognise which system is dominant is the difference between a reactive impulse and a disciplined well thought through choice.',
      'SYSTEM 1 — Fast Thinking (automatic, intuitive, emotionally driven): operates below conscious awareness; draws on pattern recognition and past experience; produces rapid, confident judgements; vulnerable to cognitive biases; dominant in high-pressure strategy sessions.\nIn practice: The gut feeling a leader has about a market opportunity — formed in seconds from years of experience.',
      'SYSTEM 2 — Slow Thinking (deliberate, analytical, effortful): requires conscious attention and cognitive effort; analyses data, weighs options, considers trade-offs; slower but more reliable for complex problems; easily overridden by System 1 under time pressure; requires psychological safety to activate.\nIn practice: The structured analysis that follows — or should follow — to validate or challenge that gut feeling.',
      'Directing participants: draw attention to the red (System 1) and green (System 2) cards side by side. Ask participants to read both, then ask: “Under what conditions does System 1 take over in your organisation? What does that look like in a meeting room?”',
      'Key facilitation point: Emphasise that the goal is to know when System 2 is needed and to create the conditions for it to activate. This frames the practical purpose of everything that follows in the unit.',
      'Participant reflection (participant file, 2.2): “Think of a significant strategic decision you were involved in recently. Which system was dominant — System 1 or System 2? What were the conditions that determined which one took over?”') });
  {
    const s = d.slide(); d.title(s, '2.3 · The Elephant Perspective');
    box(s, 0.6, 1.65, 4.2, 5.3, C.tint);
    await badge(s, 'GiElephant', 1.2, 2.4, 3.0, C.forest, C.white);
    T(s, 'Six men, one elephant', { x: 0.8, y: 5.75, w: 3.8, h: 0.6, fontSize: 24, bold: true, color: C.forest, align: 'center' });
    const parts = [['Side', 'a wall'], ['Tusk', 'a spear'], ['Trunk', 'a snake'], ['Leg', 'a tree trunk'], ['Ear', 'a fan'], ['Tail', 'a rope']];
    for (let i = 0; i < 6; i++) {
      const c = i % 2, r = Math.floor(i / 2), x = 5.1 + c * 3.9, y = 1.65 + r * 1.05;
      box(s, x, y, 3.7, 0.85, C.tint);
      T(s, [{ text: parts[i][0] + ': ', options: { bold: true, color: C.forest } }, { text: parts[i][1] }], { x: x + 0.25, y, w: 3.3, h: 0.85, fontSize: 26, valign: 'middle' });
    }
    box(s, 5.1, 4.95, 7.63, 2.0, C.forest);
    T(s, 'Each is seeing a different part of the same reality.', { x: 5.4, y: 4.95, w: 7.1, h: 2.0, fontSize: 28, fontFace: F.head, italic: true, color: C.white, valign: 'middle' });
    s.addNotes(N(
      '2.3 · FUNCTIONAL BIAS IN STRATEGY: THE ELEPHANT PERSPECTIVE (Collective Coherence)\nTime: 10–12 minutes including parable and debrief (this slide and the next).',
      'Opening provocation: before reading the parable, ask: “In your leadership team, who sees the most complete picture of the organisation’s strategic reality? What does that person’s role tell you?” Allow a brief discussion.',
      'Content:\nWhile the dual-process framework explains how individual judgement is formed, strategy in organisations is rarely an individual act. It is a collective process, shaped by multiple leaders — each bringing their own experience, expertise, and perspective.\nEven when each individual is thinking clearly within their own context, the organisation as a whole can still drift into misalignment. Each leader is seeing a different part of the same reality. Every executive leader develops deep expertise within their domain. That expertise is essential — it drives competence, speed, and confidence in decision-making. But it also creates invisible filters.\nThese filters shape: what leaders notice, how they interpret information, what they prioritise, and what they believe needs to be done. When left unexamined, these differences surface as execution friction: delayed decisions, misaligned KPIs, teams moving with energy but in different directions.',
      'Reading The Elephant Perspective: read the parable aloud yourself, or invite a participant to read it to the group. The narrative is short but requires a moment of quiet after it finishes. Resist the urge to immediately explain it.',
      'The parable (read in full):\nThere is an old story and told in many forms across many cultures — about six men who are blind from birth. One day they are led to an elephant, an animal they have heard spoken of but never encountered, and each is invited to discover it.\nThe first man reaches out and touches the side of the elephant. It is vast, flat, and solid. “An elephant,” he declares, “is like a wall.”\nThe second finds a tusk and wraps his hands around its smooth, curved length. “Not at all,” he says. “It is like a spear.”\nThe third takes hold of the trunk as it curls and twists. “You are both wrong. It is like a snake.”\nThe fourth encircles a leg and feels the rough, pillar-like mass beneath his palms. “It is a tree trunk.”\nThe fifth grasps the ear and feels its wide, flat sweep. “It is a fan.”\nThe sixth grabs the tail. “It is a rope.”\nEach man is telling the truth. And each man is completely wrong. None of them is lying. None is careless. Each has gathered real, tactile evidence and drawn a reasonable conclusion. The gap lies in their assumption that the part they touched is the whole they needed to understand.',
      'Debrief after the parable. Ask: “Who in your organisation is each blind man? Which function sees the ‘wall’? Which one sees the ‘rope’?” This should generate lively, candid discussion. Listen for the functions that are consistently named — this often surfaces the real silo structure of the organisation.'));
  }
  await d.list({ title: '2.3 · From individual accuracy to collective coherence', fontSize: 28, rows: [
    { icon: 'FaSearch', label: 'Surface', text: 'these partial truths' },
    { icon: 'FaHands', label: 'Hold', text: 'them in tension' },
    { icon: 'FaPuzzlePiece', label: 'Integrate', text: 'them into a unified understanding of reality' },
    { icon: 'FaExclamationTriangle', gold: true, label: 'Left unexamined:', text: 'delayed decisions, misaligned KPIs, teams moving with energy but in different directions' }],
    notes: N(
      '2.3 · KEY INSIGHT: FROM INDIVIDUAL ACCURACY TO COLLECTIVE COHERENCE',
      'Content: The classic “Elephant” parable illustrates a structural requirement for strategic leadership: the shift from individual accuracy to collective coherence. At the enterprise level, strategic quality is determined by an organisation’s ability to: Surface these partial truths; Hold them in tension; Integrate them into a unified understanding of reality.',
      'Key insight to reinforce: draw attention to the gold highlight box. Ask: “What would it take in your organisation to Surface, Hold, and Integrate all those partial truths?”',
      'Participant reflection (participant file, 2.3): “In your own organisation, where does the ‘Elephant Problem’ most clearly show up? Which functions or perspectives tend to see very different parts of the same strategic reality?”') });
  const fam1 = biasNotes('action'), fam2 = biasNotes('stability'), fam3 = biasNotes('interest'), fam4 = biasNotes('social');
  await d.cards({ title: '2.4 · Bias families: action-oriented and stability', cols: 2, titleBeside: true, titleSize: 28, textSize: 28, items: [
    { icon: 'FaRocket', title: 'Action-Oriented Biases', text: 'Overconfidence · Optimism · Illusion of Control · Planning Fallacy · Confirmation' },
    { icon: 'FaAnchor', title: 'Stability Biases', text: 'Anchoring · Status Quo · Loss Aversion · Sunk-Cost · Endowment' }],
    notes: N(
      '2.4 · THE COGNITIVE BIAS FAMILY: 20 TYPES ACROSS 4 FAMILIES (Interactive Explorer)\nTime: 12–15 minutes including exploration and group share-out (this slide and the next).',
      'Setting up the explorer: Tell participants there are 20 bias types across 4 families. Direct them to click a family card first, then use the buttons inside the panel to cycle through each bias type. Allow 5–7 minutes of individual exploration before facilitating a group discussion.',
      'Participant activity (participant file, Section 2.4): Step 1 — click a family card. Step 2 — click the bias name buttons to switch between the 5 types.\nAsk (guided exploration prompt): “Click on the bias family that you suspect is most active in your organisation’s strategy process. Read through each type. Which one do you recognise most immediately?”',
      'Content:\nThe thinking architecture described earlier consistently produces predictable patterns of distortion — what we recognise as cognitive biases. These biases follow identifiable patterns and tend to cluster around how leaders act, what they preserve, what they protect, and how they align with others.\nTo make the biases practical and usable in strategy conversations, scholars organise them into four bias families. Recognising these patterns makes hidden distortions visible so they can be managed deliberately.',
      'FAMILY 1 · ACTION-ORIENTED BIASES\n\n' + fam1,
      'FAMILY 2 · STABILITY BIASES\n\n' + fam2) });
  await d.cards({ title: '2.4 · Bias families: interest and social', cols: 2, titleBeside: true, titleSize: 28, textSize: 28, items: [
    { icon: 'FaShieldAlt', title: 'Interest Biases', text: 'Self-Interest · Silo · Incentive · Career-Risk · Perspective' },
    { icon: 'FaUserFriends', title: 'Social Biases', text: 'Conformity · Authority · Groupthink · Availability · Halo Effect' }],
    notes: N(
      '2.4 · GROUP DEBRIEF',
      'Group debrief: After individual exploration, go around the group and ask each person to name one bias and one organisational signal they recognised. Build a live picture of the group’s collective blind spots.',
      'Watch for (facilitation caution): Participants may drift towards naming other people’s biases. Gently redirect: “We’re here to understand the patterns so we can design better processes.”',
      'Key point to close on: Emphasise that biases are predictable patterns that show up in processes. The goal is making them visible so they can be managed deliberately. This framing reduces defensiveness and opens engagement.',
      'FAMILY 3 · INTEREST BIASES\n\n' + fam3,
      'FAMILY 4 · SOCIAL BIASES\n\n' + fam4,
      'Key sources: Kahneman & Tversky (1974, 1979) · Kahneman (2011) · Janis (1972) · Thaler (1980) · Christensen (1997) · Rosenzweig (2007) · McKinsey Quarterly (2010) · Edmondson (1999) · Asch (1951) · Jensen & Meckling (1976) · Page (2007) · Kerr (1975)',
      'Participant reflection (participant file, 2.4): “Which of the four bias families resonates most strongly with you personally? Which do you recognise most clearly in your organisation’s culture? What is one specific way this bias has shaped a strategic decision recently?”',
      'Transition: move to Section 3 · Intelligence — Why.') });

  // ── Section 3
  await d.section({ num: 3, name: 'Intelligence', anchor: 'Why', heading: 'Why bias costs — Sections 3.1 & 3.2',
    outcomes: ['Interpret how different executive roles translate the same strategy into divergent priorities that leave enterprise gaps unowned.', 'Evaluate the strategic and performance costs of unexamined bias in their organisation.'],
    notes: N(
      'SECTION 3 · INTELLIGENCE — WHY\nIntelligence — Why Behavioural Strategy Is Critical · Sections 3.1 · 3.2\nTime: 25–35 minutes for the section (3.1: 15–20 min · 3.2: 10–12 min).',
      'Section learning outcomes:\n1. Interpret how different executive roles translate the same strategy into divergent priorities that leave enterprise gaps unowned.\n2. Evaluate the strategic and performance costs of unexamined bias in their organisation.',
      'Section intent: Section 2 established what behavioural strategy is. This section answers why it matters — through a live case and quantified organisational costs. Participants who were intellectually engaged in Section 2 should become personally invested here. The MyHealth case is the turning point.',
      'Content: Behavioural biases are systematic, predictable, and cumulative. Left unmanaged, they act as a silent rot, compromising the integrity of even the most technically rigorous strategic frameworks.',
      'Transition in: ask the question on the next slide and hold the silence before moving to 3.1.') });
  await d.prompt({ label: 'Transition from Section 2', text: 'If every executive in your organisation performed perfectly within their own function, would your strategy actually deliver the result you intend?',
    notes: N(
      'TRANSITION FROM SECTION 2',
      'Ask: “If every executive in your organisation performed perfectly within their own function, would your strategy actually deliver the result you intend?”',
      'Hold the silence. Then proceed to Section 3.1.') });
  {
    const s = d.slide(); d.title(s, '3.1 · MyHealth Live: ten perspectives');
    box(s, 0.6, 1.65, 12.13, 2.1, C.forest);
    await badge(s, 'FaHospital', 0.9, 2.1, 1.1, C.gold, C.deep);
    T(s, 'A hospital chain launches a 24/7 patient portal: cut admin calls by 30%, build trust, live in 60 days.', { x: 2.3, y: 1.65, w: 10.2, h: 2.1, fontSize: 28, color: C.white, valign: 'middle' });
    const roles = Object.keys(CXO);
    for (let i = 0; i < roles.length; i++) {
      const x = 0.6 + (i % 5) * 2.465, y = 4.05 + Math.floor(i / 5) * 1.0;
      box(s, x, y, 2.2, 0.8, C.tint);
      T(s, roles[i], { x, y, w: 2.2, h: 0.8, fontSize: 26, bold: true, color: C.forest, align: 'center', valign: 'middle' });
    }
    T(s, 'Every executive hears the same words through their own professional filter.', { x: 0.6, y: 6.2, w: 12.1, h: 0.7, fontSize: 24, italic: true, color: C.muted });
    s.addNotes(N(
      '3.1 · FUNCTIONAL BIAS IN PRACTICE: THE MYHEALTH CASE (Interactive Executive Leader Explorer)\nTime: 15–20 minutes (this slide and the White Space slide).',
      'Content:\nWhen a strategic direction is announced, every executive in the room hears the same words through their own professional filter. Years of professional training shape how leaders interpret opportunity, risk, and priority.\nThe CFO listens for financial exposure. The COO hears operational feasibility. The CHRO listens for capability implications. The CMO hears the customer promise. Each interpretation is rational. Each perspective is valuable. But when these perspectives remain unspoken, functional bias begins quietly reshaping the strategy.',
      'Read aloud (setting up the case): “To become the leading patient-centric provider, we are launching the ‘MyHealth Live’ Portal. It provides 24/7 digital access to data, cuts admin calls by 30%, and builds trust through transparency. We go live in 60 days.”\nAsk: “Before we explore the executive perspectives — what is your immediate reaction to this announcement?”',
      'Participant activity (participant file, Section 3.1): each participant clicks the role card closest to their own function or most relevant to their organisation, and reads the internal translation and success definition. Give them a moment.\nAsk: “Does this match what you would have been thinking?”',
      'The ten perspectives (internal translation · definition of success):\n' + cxoNotes,
      'Group debrief — the competing perspectives: take 2–3 role combinations (e.g. CTO vs CMO, or CEO vs CHRO).\nAsk: “Where do these two perspectives create friction? What happens if both leaders pursue their definition of success without talking to each other?”',
      'Why This Matters: Every executive delivered a “result.” But if they don’t talk to each other about how those results compete (e.g., the CTO’s security versus the CMO’s ease of use), the strategy will eventually fracture. Alignment means acknowledging these different perspectives and deciding, together, which one takes priority at each stage of the journey.',
      'Next: expand the White Space (next slide).'));
  }
  await d.stat({ title: '3.1 · The White Space', big: '40%', caption: 'spike in ‘panic visits’ to Emergency Rooms, despite perfect scores',
    rows: [{ icon: 'FaCheck', label: 'Vertical Success:', text: 'Does my “Done” actually create more work for you?' },
      { icon: 'FaCheck', label: 'White space:', text: 'If the system is “Green” but the customer is “Red”, where do we neutralise the impact?' },
      { icon: 'FaCheck', label: 'Enterprise Consequence:', text: 'Has the enterprise won?' }],
    notes: N(
      '3.1 · THE WHITE SPACE — THE PANORAMIC SCAN (key facilitation moment)',
      'Content:\n“If every single person in this room performed perfectly within their own silo, would we actually get the result we’re after?”\nDespite perfect scores, the Emergency Rooms saw a 40% spike in ‘panic visits’ from patients who received raw, uninterpreted lab results at 9:00 PM on a Friday. Customer Satisfaction (NPS) plummeted because patients felt overwhelmed.\nThis is the WHITE SPACE — the unspoken friction between the functions — the hand-offs, the emotional context of the patient — that no one owned, even though everyone hit their targets.\nThe “White Space” is the gap between functional mandates where no one is technically “in charge,” but where the patient/customer/value experience actually lives.',
      'Three-point check to colour the white space (read aloud):\n1. Does my “Done” actually create more work for you? — Vertical Success\n2. If the system is “Green” but the customer/employee is “Red,” where do we neutralise the impact? — White space\n3. Has the enterprise won? — Enterprise Consequence',
      'Ask: “In your current strategy — where is the enterprise consequence that nobody formally owns?” This is often where the most candid and valuable conversation in the session occurs. Give it space.',
      'Participant reflection (participant file, 3.1): “Select the executive leader role that is most relevant to you. What does the internal translation reveal about your own blind spots? Where is the ‘White Space’ in your organisation’s current strategy — the gap between functional success and enterprise outcome?”') });
  await d.stat({ title: '3.2 · The hidden cost of poor behavioural awareness', big: '≈6%', caption: 'higher returns where decision-making actively mitigates bias (McKinsey)',
    rows: [{ icon: 'FaCoins', label: 'Misallocated Capital', text: 'Stability & Action Biases' },
      { icon: 'FaMountain', label: 'Strategic Inertia', text: 'Stability Biases' },
      { icon: 'FaBolt', label: 'Execution Failure', text: 'Action-Oriented Biases' },
      { icon: 'FaVolumeMute', label: 'Innovation Suppression', text: 'Social & Interest Biases' },
      { icon: 'FaRoute', label: 'Purpose Drift', text: 'Interest & Social Biases' }],
    notes: N(
      '3.2 · THE HIDDEN COST OF POOR BEHAVIOURAL AWARENESS (5 Strategic Costs)\nTime: 10–12 minutes.',
      'Opening the section. Before expanding any cost item, ask: “If I told you that disciplined decision-making delivers approximately 6% higher returns than the norm — what would that mean in real terms for your organisation?” Let the number land before proceeding.',
      'Content: Research by McKinsey & Company indicates that organisations with disciplined decision-making practices — specifically those that actively mitigate cognitive bias — deliver returns approximately 6% higher than their peers. Conversely, a lack of behavioural awareness creates a “hidden tax” on the organisation:\n- Misallocated Capital (Stability & Action Biases): Resources are funnelled into legacy lines due to Sunk-Cost Fallacy and the Endowment Effect. New “ego acquisitions” are often fuelled by Overconfidence and the Illusion of Control, prioritising ambition over future value.\n- Strategic Inertia (Stability Biases): The organisation recognises disruption but is paralysed by Anchoring Bias to old metrics and a powerful Status Quo Bias. The fear of change (Loss Aversion) prevents the “dominant coalition” from shifting to new models.\n- Execution Failure (Action-Oriented Biases): High-level plans collapse because they are built on the Planning Fallacy and Optimism Bias. Leaders fail to account for internal friction because they are blinded by an Action-Reinforcing Confirmation Bias.\n- Innovation Suppression (Social & Interest Biases): Transformative ideas are filtered out by Groupthink and Conformity Bias. Potential dissenters remain silent due to Career-Risk Bias, fearing that challenging the “Alpha” strategy will impact their trajectory.\n- Purpose Drift (Interest & Social Biases): Long-term intent is sacrificed to Self-Interest and Incentive Bias. Short-term pressures trigger emotional responses that allow the Halo Effect of a “quick win” to override long-term strategic commitments.',
      'Participant activity (participant file, Section 3.2): participants click through each cost item themselves. After they have read all five, ask: “Which of these is the most expensive one in your organisation right now — and which is the most invisible?”',
      'Pair or small group discussion (if time allows): divide participants into pairs; each pair identifies the cost they believe is most active and traces it back to a specific bias family from Section 2.4. Bring back to the full group for a 2-minute share-out.',
      'Participant reflection (participant file, 3.2): “Which of the five hidden costs is most visible in your current organisation? Can you trace it back to a specific bias family? What would it take to address it?”',
      'Transition (closing point for Section 3): “Now that we know what bias costs, the next question is: where exactly in the strategy process do these costs accumulate? That’s what Section 4 maps for us.”') });

  // ── Section 4
  await d.section({ num: 4, name: 'Extrapolating', anchor: 'Where', heading: 'The bias landscape · The emotional dimension',
    outcomes: ['Identify where bias and emotional climate most affect decision quality across the strategy process.', 'Determine the interventions that would most strengthen objectivity in their own strategy process.'],
    notes: N(
      'SECTION 4 · EXTRAPOLATING — WHERE\nExtrapolating — Where Behavioural Strategy Operates\nTime: 35–45 minutes across both chapters (4.1: 15–20 min · 4.2: 10–12 min · 4.4: 10–12 min).',
      'Section learning outcomes:\n1. Identify where bias and emotional climate most affect decision quality across the strategy process.\n2. Determine the interventions that would most strengthen objectivity in their own strategy process.',
      'Section intent: This is the most diagnostic section. Participants move from understanding bias conceptually to mapping where it shows up — across their own strategy process (4.1) and in the emotional environment that either amplifies or dampens it (4.2 to 4.4). Expect this section to surface uncomfortable recognitions. That is the design intent.',
      'Say (framing for the group): “Every bias we explored in Section 2 has a home. It lives in specific moments of the strategy process. This section maps those moments.”') });
  const phase = (title, a, b, notes) => d.cards({ title, cols: 2, titleBeside: true, titleSize: 28, textSize: 26, items: [a, b], notes });
  await phase('4.1 · The bias landscape: diagnosis and options',
    { icon: 'FaSearch', title: 'Phase 1 · Diagnosis', text: 'Wrong reality enters the strategy\n\nAvailability · Anchoring · Confirmation' },
    { icon: 'FaStream', title: 'Phase 2 · Option Generation', text: 'Solution space narrowed before debate\n\nStatus Quo · Groupthink · Career-Risk · Silo' },
    N(
      '4.1 · THE STRATEGY JOURNEY AS A BIAS LANDSCAPE (4 Phases)\nTime: 15–20 minutes (this slide and the next).',
      'Directing participants through the phase tabs: Walk through each of the four phase tabs as a group — do not allow individual browsing at this stage. For each phase, read the relevant content aloud or ask a participant to read it, then pause on the scanner question at the end of each panel.',
      'Using the scanner questions as live diagnostics: At each phase, ask the group to answer the scanner question for their own organisation, right now. Capture responses on a whiteboard or shared screen if possible. This creates a real-time bias exposure map for the group’s actual strategy process.',
      'Content:\nStrategy enters the organisation through people before it becomes execution. Every strategic message is filtered through the mind (cognition) and the heart (emotion). Bias lives in processes as well as in people. More precisely, it lives in the specific moments within a strategy process where human judgement is required — where data must be interpreted, options must be imagined, choices must be made, and plans must be translated into action.\nThis is the core insight of the extrapolating zone: behavioural strategy is a practical map of where, in the ordinary course of strategy management, your organisation is most exposed to invisible error.',
      'PHASE 1 · DIAGNOSIS — Wrong reality enters the strategy\nEvery strategy begins with a reading of reality. Leaders scan the external environment, assess internal capability, and form a view of what is true about the organisation’s position. This diagnostic work provides the foundation on which everything else is built. It is also where the first — and most consequential — distortions enter.\nThe problem is that the human mind cannot process all available information equally. It selects. And the criteria for selection are rarely objective.\n- Availability Bias governs what gets noticed. Information that is recent, vivid, or frequently discussed is weighted far above its actual strategic significance. A competitor’s recent product launch or a difficult quarter just closed can dominate diagnostic conversations in ways that distort the overall picture.\n- Anchoring Bias governs what gets used as a reference point. The first number on a slide, the previous year’s result, the analyst’s initial estimate — these become gravitational centres around which all subsequent thinking orbits. The frame is set before analysis begins.\n- Confirmation Bias closes the loop. Once leaders have formed an initial view — however provisional — they unconsciously seek information that supports it. Disconfirming data is given less weight, processed more sceptically, and remembered less reliably.\nA strategy built on a flawed diagnosis is a well-organised response to a problem the organisation has imagined.\nScanner Question: “If we stripped out everything our team already knew or believed before this process began, what would the remaining evidence actually tell us?”\nAsk (Phase 1 — Diagnosis): “Is your current strategic diagnosis based on data you deliberately sought — or data that happened to be available?”',
      'PHASE 2 · OPTION GENERATION — Solution space narrowed before debate\nThis phase should be the most generative in the strategy process. It is where imagination, expertise, and creative tension produce the range of paths from which a choice will eventually be made. In practice, it is often the most constrained. The constraint is the invisible narrowing that happens before options are ever formally tabled — through social dynamics, professional filters, and unspoken norms about what is realistic to propose.\n- Status Quo Bias is the most pervasive. The current strategy naturally pulls thinking toward what already exists. Teams tend to make small adjustments to the current approach and leave bold or different options unexplored.\n- Functional and Silo Bias means that options tend to be generated inside each organisational lane. The genuinely transformative options — those that require cross-functional integration and new ways of working — are structurally disadvantaged in the generation process.\n- Career-Risk Bias is perhaps the most damaging and least visible. Leaders and their teams have a well-developed instinct for what it is safe to propose. Radical options carry personal risk for the people who advocate them. So they do not get advocated. They may not even get thought.\n- Groupthink and Conformity Bias operate in the room itself. Once a dominant view begins to form — even loosely — the social pressure to align with it grows. Dissenting options require social courage as well as intellectual effort. In most rooms, courage is in shorter supply than intelligence.\nThe options that reach a decision are the options that survived a social and professional filter that operated before the formal process began.\nScanner Question: “What is the most disruptive option we have not yet put on the table — and what is the real reason it is not there?”\nAsk (Phase 2 — Option Generation): “How many genuinely different strategic options did your team consider before committing to your current direction?”'));
  await phase('4.1 · The bias landscape: decision and execution',
    { icon: 'FaGavel', title: 'Phase 3 · Decision', text: 'Chosen path flawed or skewed\n\nOverconfidence · Loss Aversion · Authority · Halo · Sunk-Cost' },
    { icon: 'FaCogs', title: 'Phase 4 · Execution', text: 'Strategy decays in delivery\n\nPlanning Fallacy · Incentive · Self-Interest · Confirmation' },
    N(
      '4.1 · PHASES 3 AND 4',
      'PHASE 3 · DECISION — Chosen path flawed or skewed\nThe decision phase is especially vulnerable because of how people think under pressure. As a choice gets closer, the need for certainty replaces comfort with uncertainty. Confidence increases, even when not fully justified. The dynamics in the room — who has authority, who is most respected, and who has the most to gain or lose — start to influence the outcome more than the actual evidence.\n- Overconfidence Bias inflates the perceived quality of the chosen option. Once a direction is favoured, its upsides are weighted generously and its risks are managed down. The analysis looks thorough. The underlying confidence is often unearned.\n- Loss Aversion tilts the scales in a particular direction. When two options are genuinely close in expected value, the one that protects existing positions will almost always prevail over the one that requires exposure to new risk.\n- Authority Bias and the Halo Effect determine whose judgement prevails in the room. The most senior voice, the most admired leader, the external advisor with the strongest reputation — these sources of input receive disproportionate weight regardless of the evidence behind them.\n- The Sunk-Cost Fallacy and the Endowment Effect shape which portfolio options survive. Decisions that would require writing down prior investment or divesting something the organisation has built are systematically disadvantaged by what has already been put in, whatever their merit.\nThe moment of decision is when the pressure to commit is highest and the tolerance for challenge is lowest.\nScanner Question: “If the person who proposed this option had no stake in the outcome, and no prior relationship with the team, would we make the same decision?”\nAsk (Phase 3 — Decision): “Who had the most influence over your last major strategic call — and was that influence based on evidence or authority?”',
      'PHASE 4 · EXECUTION — Strategy decays in delivery\nThe strategy is set. The decision has been made. At this point, leaders often assume that the main risks are behind them. This is a mistake. Bias continues into execution. It changes form — and can become even more costly. Execution requires teams to stay aligned, report honestly on what is happening, and recognise quickly when things need to change.\n- The Planning Fallacy means the execution plan was almost certainly undercooked from the start. Timelines were too optimistic. Resource estimates were too lean. The complexity of interdependencies was underweighted.\n- Confirmation Bias in its action-reinforcing form means green indicators are noted, amber ones rationalised, red ones attributed to temporary factors. By the time the evidence is undeniable, the window for course correction has narrowed considerably.\n- Incentive Bias fractures alignment. Leaders pursue what they are rewarded for. When incentives and strategy diverge, strategy loses. Consistently.\n- Self-Interest and Functional Bias fragment what the strategy requires to be integrated. The horizontal coordination that execution demands — the willingness to prioritise enterprise outcomes over functional ones — runs directly against the grain of how most organisations are structured.\nExecution failure is usually a continuation of the same behavioural problems that shaped the strategy — now playing out in a context where they are harder to see and more expensive to correct.\nScanner Question: “Are we measuring what matters to the strategy, or measuring what is easy to measure — and whose interests does the current reporting structure actually serve?”\nAsk (Phase 4 — Execution): “If your current strategy is off-track, how quickly would you know — and what would stop you from acting on it?”',
      'Key facilitation point: Participants often locate their organisation primarily in Phase 3 or 4. Challenge this — ask them to go back to Phase 1 and examine whether the diagnosis was clean before the decision was ever made.',
      'Participant reflection (participant file, 4.1): “At which of the four phases is your organisation currently most exposed? Use the scanner question for that phase to frame your answer. What would it mean for your strategy process if you addressed that phase more deliberately?”'));
  await d.cards({ title: '4.2 · The emotional climate as atmospheric pressure', cols: 3, items: [
    { icon: 'FaExclamationTriangle', title: 'Fear-Dominated', text: 'Strategic Paralysis · System 1 Hijack' },
    { icon: 'FaCrown', title: 'Narcissism-Dominated', text: 'Strategic Delusion · Validation Loop' },
    { icon: 'FaSeedling', title: 'Grounded Confidence', dark: true, text: 'Strategic Agility · System 2 Optimisation' }],
    band: 'For a leader, managing the emotional climate is a fiduciary responsibility.',
    notes: N(
      '4.2 · THE EMOTIONAL CLIMATE AS ATMOSPHERIC PRESSURE (The Emotional Dimension of Strategy · Sections 4.2 · 4.3 · 4.4)\nTime: 10–12 minutes.',
      'Opening the section. Before showing the climate tabs, ask: “In one word, what is the dominant emotional state in your leadership team’s strategy conversations right now?” Ask 3–4 participants. Write the words on a whiteboard or flip chart. This creates a live emotional map of the room before the framework is introduced.',
      'Content:\nThe Emotional Climate of the organisation or team is the atmospheric pressure that determines whether the organisation’s “Thinking Architecture” functions or freezes.\nAs Quy Nguyen Huy’s research suggests, emotions are the “gatekeepers” of System 2 thinking. Emotions control whether careful thinking happens. In a climate of fear or ego, people rely more on instinct (System 1) and less on deliberate, analytical thinking (System 2).\nThe emotional tone set by senior leadership shapes how the organisation thinks and responds over time. When leaders are not open to feedback, challenge, or new perspectives, the organisation also becomes less responsive. This creates strategic closure — a condition where the organisation continues on a path without properly testing whether it is still the right one.\nFor a leader, managing the emotional climate is a fiduciary responsibility. If you allow a climate of fear or narcissism to take root, you are effectively dismantling the organisation’s ability to process reality.',
      'FEAR-DOMINATED\nThe Emotional Driver: Anxiety & Defence: The primary goal is the avoidance of blame or punishment.\nThe Strategic Outcome: Strategic Paralysis: Strategy is reduced to incrementalism. Leaders favour “safe” bets to avoid the personal cost of failure.\nImpact on Thinking Architecture: System 1 Hijack: The brain is in “threat mode.” Dissent is viewed as dangerous, triggering Conformity and Career-Risk Biases.',
      'NARCISSISM-DOMINATED\nThe Emotional Driver: Ego & Grandiosity: The strategy serves as a monument to the leader’s identity, detached from the market.\nThe Strategic Outcome: Strategic Delusion: Grandiose plans are launched with zero operational grounding. “Vision” is treated as infallible, overriding data.\nImpact on Thinking Architecture: Validation Loop: System 2 is used exclusively to justify the leader’s Overconfidence and Illusion of Control. Confirmation Bias is institutionalised.',
      'GROUNDED CONFIDENCE\nThe Emotional Driver: Curiosity & Security: The focus is on objective truth-seeking and collective intelligence.\nThe Strategic Outcome: Strategic Agility: The organisation practices iterative strategy. It can “fail fast” because the ego is decoupled from the outcome.\nImpact on Thinking Architecture: System 2 Optimisation: High psychological safety allows for Structured Dissent. Biases are caught early because the climate rewards the “auditing” of ideas.',
      'Directing through the three climate tabs: click through each climate type one at a time. For each, ask: “Raise your hand if you have personally experienced this climate at any point in your career.” This normalises the conversation and reduces defensiveness.',
      'Key facilitation point: Emphasise the red highlight box — managing the emotional climate is a fiduciary responsibility. Ask: “What does it cost your organisation when the climate is wrong — and who is accountable for that?”',
      'Transition to Section 4.3: Once the three climate types are understood, move to Section 4.3 to explore the emotional states that operate within any climate.') });
  await d.list({ title: '4.3 · Emotional alignment: the state of being', fontSize: 28, rows: [
    { icon: 'FaBolt', label: 'Engagement Energy', text: '' }, { icon: 'FaBatteryQuarter', label: 'Morale Drain', text: '' },
    { icon: 'FaCompressArrowsAlt', label: 'Friction Load', text: '' }, { icon: 'FaShieldAlt', label: 'Psychological Safety', text: '' },
    { icon: 'FaHandshake', label: 'Values Alignment', text: '' }],
    notes: N(
      '4.3 · EMOTIONAL ALIGNMENT: IDENTIFYING THE STATE OF BEING',
      'Purpose of this section: This section moves from the macro climate to the individual and team emotional states that strategy lands into. It is practical and diagnostic — encourage participants to apply it to a current project or decision.',
      'Content: Emotional alignment is achieved by explicitly naming the current emotional state through which strategy is being experienced. Strategy always lands into an emotional climate before it lands into action. Leaders and teams operate from a dominant state of being, commonly expressed across Ekman’s Six Basic Emotions: Joy · Sadness · Anger · Fear · Disgust · Surprise.\nEach state influences:\n- Engagement Energy — the level of discretionary effort, momentum, and willingness to contribute beyond minimum requirements.\n- Morale Drain — the degree to which emotional fatigue, disappointment, or disengagement reduces capacity and persistence.\n- Friction Load — the amount of hidden resistance, tension, or drag experienced in decisions, collaboration, and follow-through.\n- Psychological Safety — the extent to which individuals feel safe to speak, challenge, admit uncertainty, and take appropriate risk.\n- Values Alignment — the consistency between stated values, observed leadership behaviour, and everyday decisions under pressure.',
      'Directing participants: Read the five factors aloud. After each one, ask participants to give a private rating of 1–5 for their current team. This creates a personal baseline they can return to at the end of the unit.',
      'Key insight to reinforce: draw attention to the highlight box — “Unacknowledged emotional states silently override rational plans.” Ask: “What is the unacknowledged emotional state in your organisation’s current strategy cycle?” This is often the most candid question in the entire unit — give it time.',
      'Participant reflection (participant file, 4.2–4.3): “Which climate type best describes your team or organisation right now? What specific leadership behaviours are creating or sustaining that climate? What is the cost of that climate to the quality of your strategy work?”') });
  await d.list({ title: '4.4 · Six principles for debiasing strategy', fontSize: 24, rows: [
    { icon: 'FaLightbulb', label: '1', text: 'Separate ideation from evaluation.' },
    { icon: 'FaThermometerHalf', label: '2', text: 'Name the emotional temperature before the strategic content.' },
    { icon: 'FaGavel', label: '3', text: 'Assign a designated challenger role.' },
    { icon: 'FaFlask', label: '4', text: 'Use pre-mortem analysis as standard practice.' },
    { icon: 'FaLayerGroup', label: '5', text: 'Make the reference class visible.' },
    { icon: 'FaHistory', label: '6', text: 'Create after-action protocols.' }],
    notes: N(
      '4.4 · DEBIASING PRINCIPLES FOR STRATEGY MANAGEMENT\nTime: 10–12 minutes.',
      'Say (framing the section): “The goal now is to change how we design our strategy processes.” This is where the unit becomes actionable.',
      'Content: Awareness alone does not change outcomes. Without deliberate intervention, the same biases will continue to shape strategic conversations and decisions.\nWhat matters is how strategy processes are designed — who speaks, how options are generated, how challenge is introduced, and how decisions are tested. These design choices determine whether thinking becomes clearer or more distorted.\nThe principles below — adopted from the works of Kahneman, Lovallo, Sibony, Huy, Lencioni, and Edmondson — provide practical ways to strengthen the quality of the strategy management process:',
      '1. Separate ideation from evaluation. Apply this principle whenever options, solutions, or responses are being generated — whether in strategy design, problem-solving, or execution reviews. Protect the generative phase from early criticism. Premature judgement reduces the range and quality of options considered. Use a structured divergent-then-convergent approach to ensure all viable possibilities are surfaced before evaluation begins.\n2. Name the emotional temperature before the strategic content. At the start of any critical conversation — strategy, performance, or course correction — surface the emotional state in the room. A simple question such as “What emotions are people bringing into this discussion that might affect how we think?” helps shift the group from reactive thinking to deliberate engagement. This strengthens focus, reduces hidden tension, and enables more honest dialogue.\n3. Assign a designated challenger role. In all high-stakes decisions, including strategy formulation, assign a rotating challenger role. The responsibility is to test assumptions, question prevailing views, and present credible alternatives. This ensures decisions are pressure-tested before and during execution, reducing the risk of blind spots and unchallenged momentum.\n4. Use pre-mortem analysis as standard practice. Apply pre-mortems before setting direction and before major initiatives, launches, or execution phases. Ask: “If this fails, what are the most likely reasons?” This surfaces risks early, improves planning quality, and strengthens execution readiness by addressing failure points in advance.\n5. Make the reference class visible. At every stage — planning, execution, and review — ground decisions in real-world evidence. Compare current plans and performance against similar initiatives in comparable conditions. This reduces overconfidence, improves forecasting, and anchors judgement in external reality.\n6. Create after-action protocols. Institutionalise regular, structured learning reviews throughout execution, from start to finish. Focus on understanding what the environment revealed, and how thinking and decisions shaped outcomes. This builds an ongoing learning system that strengthens adaptation while results can still be influenced.',
      'Participant activity (participant file, Section 4.4): participants click each numbered principle, read all six silently and select the one they feel is most absent from their current practice. Allow 3 minutes for individual reading.',
      'Group debrief. Ask: “Which principle does your organisation consistently skip — and what does that cost you?” Then: “Which one could you introduce into your very next strategy meeting without needing anyone’s permission?”',
      'Participant reflection (participant file, 4.4): “Which of these six principles do you currently apply most consistently? Which is most absent from your current practice? What would it look like to introduce one of the absent principles into your next important decision or meeting?”',
      'Closing the Extrapolating section: pause before moving to Section 5. Ask participants to reflect: “You have now mapped where your organisation is most exposed and why. What is the one thing you are most committed to changing?” Brief pair share before moving on.') });

  // ── Section 5
  await d.section({ num: 5, name: 'Integration', anchor: 'Collective', heading: 'From individual thinking to collective intelligence',
    outcomes: ['Recognise the conditions that turn individual perspectives into collective intelligence within a leadership team.', 'Prioritise the organisational practices that would most strengthen collective decision quality.'],
    notes: N(
      'SECTION 5 · INTEGRATION — COLLECTIVE\nIntegration — How to Build Collective Intelligence · Sections 5.1 · 5.2\nTime: 30–40 minutes (5.1: 12–15 min · 5.2: 12–15 min).',
      'Section learning outcomes:\n1. Recognise the conditions that turn individual perspectives into collective intelligence within a leadership team.\n2. Prioritise the organisational practices that would most strengthen collective decision quality.',
      'Section intent: This section is where the unit moves from diagnosis to design. Participants have identified what behavioural strategy is, why it matters, and where biases operate. Now they learn how to build an environment where collective intelligence can actually function. This is the most practically actionable section — treat it that way.',
      'Say (framing the transition): “Everything we have covered so far reveals the problem. This section is about the solution architecture. It designs better environments for judgement.”') });
  await d.prompt({ icon: 'FaUsers', label: 'Opening Context', text: 'Integration is where the “Me” becomes “We.”',
    foot: 'At which phase in your current strategy process are you most exposed?',
    notes: N(
      'OPENING CONTEXT (Foundation)',
      'Opening the section. Ask: “If everyone in your leadership team performed at their personal best — would the quality of your collective decisions automatically improve?” The expected answer is yes. The correct answer is not necessarily. Allow the tension to sit before revealing the content.',
      'Content:\nThe quality of strategy execution is a direct function of the quality of the thinking environment: the conditions under which thinking happens.\nIn the Integration section, we solve the “Elephant Perspective” problem. We do this by moving from functional silos to an Enterprise-Wide Perspective. This requires shifting the leadership team from “Defending the Part” to “Designing the Whole.”\nIntegration is where the “Me” becomes “We.” It’s the process of trading individual opinions for Collective Intelligence.',
      'The key shift: draw attention to the gold highlight. Ask: “What does your current strategy process do to actively create that shift — or does it assume it will happen naturally?”',
      'The diagnostic question (gold panel, “The Question for Every Leadership Team”): At which phase in your current strategy process are you most exposed? Where is the quality of your thinking least protected? The answer to that question is where your debiasing effort should begin.\nAsk participants to answer it privately in writing before moving to Section 5.1.',
      'Participant reflection (participant file, Opening Context): “What does ‘integration’ currently look like in your organisation? Where does the transition from individual perspectives to a shared enterprise view most often break down?”') });
  await d.cards({ title: '5.1 · The three pillars of integration', cols: 3, items: [
    { icon: 'FaPuzzlePiece', title: 'Cognitive Integration', text: 'Build a single version of the truth.' },
    { icon: 'FaStopwatch', title: 'Behavioural Guardrails', text: 'Stop the “loudest voice” winning by default.' },
    { icon: 'FaHandHoldingHeart', title: 'Emotional Stabilisation', text: 'Move the team from defensiveness to curiosity.' }],
    band: 'The pillars reinforce each other.',
    notes: N(
      '5.1 · THE THREE PILLARS OF INTEGRATION\nTime: 12–15 minutes.',
      'Before exploring the pillars. Ask: “Without looking at the screen — what do you think the biggest structural barrier to genuine collective intelligence is in your organisation?” Take 3–4 responses. Then navigate to the first pillar and show how the framework responds to those exact barriers.',
      'PILLAR 1 · COGNITIVE INTEGRATION: CONNECTING THE DOTS\nThis is about breaking down the “I’m an expert in my area” silos. If Marketing only sees customers and Finance only sees costs, they are both looking at a fragmented reality.\nThe Goal: Build a single version of the truth.\nHow it works: You require every department to explain how its information affects everyone else.\nIn Practice: A “Stress Test” where the team asks: “If the Finance data is right, does the Marketing plan still make sense?”',
      'PILLAR 2 · BEHAVIOURAL GUARDRAILS: PUTTING UP SAFETY NETS\nSmart people make bad choices when they rush. Guardrails are simple rules that force your brain to slow down and switch from “Gut Feel” (System 1) to “Logic” (System 2).\nThe Goal: Stop the “loudest voice” or the “fastest talker” from winning by default.\nHow it works: You build “friction” into the meeting. You make it a requirement to disagree before a final vote is taken.\nIn Practice: The Challenge Clock — Dedicate 10 minutes to only finding reasons why the plan won’t work.',
      'PILLAR 3 · EMOTIONAL STABILISATION: CLEARING THE AIR\nIf a room is full of fear or big egos, no one tells the truth. Stabilisation is about making the environment “safe” enough for high-level thinking.\nThe Goal: Move the team from defensiveness to curiosity.\nHow it works: Leaders must admit they don’t have all the answers. This lowers the “atmospheric pressure” and lets the team speak up without fear of looking bad.\nIn Practice: Naming the Feeling — Start by saying, “I know we’re all anxious about this deadline. Let’s acknowledge that before we look at the numbers.”',
      'Directing through the three pillar tabs: click through each pillar one at a time. For each, ask: “Is this pillar present in your current strategy process — and if so, what does it look like in practice?”',
      'Identifying the weakest pillar: after all three, ask each participant to privately identify which pillar is most underdeveloped in their current environment. Invite 3–4 to share their answer and their reason. This is often the most direct conversation in the section.',
      'Key facilitation point: Remind the group that all three pillars are interdependent. A strong Cognitive Integration process will collapse in a fear-dominated climate (Pillar 3 failure). Guardrails will be bypassed if there is no psychological safety to use them (Pillar 3 again). The pillars reinforce each other.',
      'Participant reflection (participant file, 5.1): “Which of the three pillars is most underdeveloped in your current team or organisation? What is one specific practice from that pillar that you could introduce in your next strategy meeting or working session?”') });
  await d.list({ title: '5.2 · In the Strategy Room', fontSize: 26, rows: [
    { icon: 'FaBook', label: '72-Hour Pre-Read Mandate', text: 'Anchoring' },
    { icon: 'FaSyncAlt', label: 'Rotating Neutral Facilitation', text: 'Authority Bias & Groupthink' },
    { icon: 'FaUserSecret', label: 'Blind Ideation', text: 'Conformity & Halo Effect' },
    { icon: 'FaStopwatch', label: 'The “Challenge Clock”', text: 'Action-Oriented rush' },
    { icon: 'FaPenFancy', label: 'Silent Deliberation', text: 'Availability Bias' }],
    notes: N(
      '5.2 · INSTITUTIONAL PRACTICES FOR COLLECTIVE INTELLIGENCE (10 Practices)\nTime: 12–15 minutes (this slide and the next). The label after each practice on the slide is the bias it neutralises.',
      'Say (framing the section): “The principles in Section 4.4 told you what to do. These practices tell you how to embed it structurally — so it doesn’t depend on one person’s intention or memory.”',
      'Content: What must exist in the organisation for good thinking to happen consistently. These are structural changes to how strategy is conducted.',
      'IN THE STRATEGY ROOM\n- 72-Hour Pre-Read Mandate (Neutralises: Anchoring): Strategic documents distributed 3 days prior to the session. Prevents Anchoring to the presenter’s live framing and allows for independent reflection.\n- Rotating Neutral Facilitation (Neutralises: Authority Bias & Groupthink): Sessions are led by someone other than the CEO or the most senior executive. Neutralises Authority Bias and Groupthink by decoupling power from the process.\n- Blind Ideation (Neutralises: Conformity & Halo Effect): Anonymous submission of ideas and critiques during the exploration phase. Eliminates Conformity Bias and the Halo Effect of senior-led suggestions.\n- The “Challenge Clock” (Neutralises: Action-Oriented rush): A dedicated, non-negotiable segment on the agenda for dissenting views. Forces System 2 engagement and protects against the Action-Oriented rush to decide.\n- Silent Deliberation (Neutralises: Availability Bias): Individual written reflection is required before any verbal group discussion. Prevents the “First Voice” from dominating and triggering Availability Bias.',
      'Participant activity (participant file, Section 5.2): participants explore “In the Strategy Room” first, then “In Leadership Culture”. They read each practice and mark — mentally or in writing — which ones are already active, which are partially active, and which are absent.') });
  await d.list({ title: '5.2 · In Leadership Culture', fontSize: 26, rows: [
    { icon: 'FaGlasses', label: 'Public Cognitive Humility', text: 'Overconfidence' },
    { icon: 'FaSyncAlt', label: 'Behavioural 360s', text: 'Self-Interest & Perspective' },
    { icon: 'FaUserCheck', label: 'Debiasing Coaching', text: 'System 1 dominance' },
    { icon: 'FaShieldAlt', label: 'Safety Metrics', text: 'Innovation Suppression & Career-Risk' },
    { icon: 'FaHistory', label: 'Strategic Post-Mortems', text: 'Hindsight Bias' }],
    notes: N(
      '5.2 · IN LEADERSHIP CULTURE',
      'IN LEADERSHIP CULTURE\n- Public Cognitive Humility (Neutralises: Overconfidence): Leaders explicitly share past errors and the logic used to correct them. Reduces the Overconfidence Bias and models a culture of continuous learning.\n- Behavioural 360s (Neutralises: Self-Interest & Perspective): Leadership assessments that measure self-awareness and decision-making rigour. Addresses Self-Interest and Perspective Bias through external feedback loops.\n- Debiasing Coaching (Neutralises: System 1 dominance): Professional development focused on identifying personal “cognitive signatures.” Builds the “muscle” for System 2 thinking under high-pressure conditions.\n- Safety Metrics (Neutralises: Innovation Suppression & Career-Risk): Using psychological safety surveys as a “Lead Indicator” for strategy quality. Ensures the absence of Innovation Suppression and Career-Risk Bias.\n- Strategic Post-Mortems (Neutralises: Hindsight Bias): Radical transparency regarding why a strategy succeeded or failed. Dismantles Hindsight Bias and provides a database of organisational learning.',
      'Group debrief. Ask: “Which practice is most immediately implementable in your organisation without needing a mandate from above? What is stopping you from introducing it in your next meeting?”',
      'Prioritisation exercise: Ask each participant to select their top two or three practices and share one with the group along with the bias it directly addresses. This connects the institutional practices back to the bias families explored in Section 2.',
      'Participant reflection (participant file, 5.2): “Which two or three institutional practices are most immediately implementable in your context? What resistance might you encounter, and how would you address it?”',
      'Transition: move to Section 6 · Application — In Practice.') });

  // ── Section 6
  await d.section({ num: 6, name: 'Application', anchor: 'In Practice', heading: 'The Distortion Lab and the Five Commitments Assessment',
    outcomes: ['Assess their own leadership conduct against the behavioural conditions for sound strategic judgement.', 'Commit to the development priority with the greatest effect on their strategic judgement.'],
    notes: N(
      'SECTION 6 · APPLICATION — IN PRACTICE\nApplication — Behavioural Strategy in Practice\nTime: 40–55 minutes including simulation debrief and assessment (Distortion Lab: 20–25 min · 6.1: 15–18 min · then Unit Summary).',
      'Section learning outcomes:\n1. Assess their own leadership conduct against the behavioural conditions for sound strategic judgement.\n2. Commit to the development priority with the greatest effect on their strategic judgement.',
      'Section intent: This is the integration section. Everything learned across Sections 1–5 is now applied — first in a live simulation (the Distortion Lab) and then in a personal self-assessment (Section 6.1). Do not skip the simulation. It is where the concepts become visceral.',
      'Say (framing for participants): “In every section so far, we have been thinking about bias. Now we are going to experience it. The Distortion Lab is designed to show you how bias operates in real-time, even when you know it exists.”') });
  await d.list({ title: 'The Distortion Lab: The Growth Decision', fontSize: 26, rows: [
    { icon: 'FaUsers', label: 'Groups of 4–6:', text: 'different functions represented' },
    { icon: 'FaBookOpen', label: '5 minutes:', text: 'read the scenario individually and silently' },
    { icon: 'FaUserTie', label: 'Assigned roles:', text: 'no self-selection' },
    { icon: 'FaComments', label: '10–12 minutes:', text: 'discussion without facilitator intervention' },
    { icon: 'FaHandPaper', gold: true, label: 'Stop before consensus:', text: 'has anyone identified the white space yet?' }],
    notes: N(
      'THE DISTORTION LAB: THE GROWTH DECISION (Integration Simulation · Printable)\nTime: 20–25 minutes including setup, exercise, and debrief (slides 33–36).',
      'Preparation: Print the exercise using the gold “Print Exercise” button in the facilitator file before the session begins. Each group needs one printed copy, or participants can work from the screen. Groups of 4–6 work best — assign roles across the group so that different functions are represented.',
      'Participant activity: Participants complete this activity in their own file (Section 6 · The Distortion Lab: The Growth Decision). Their file holds the objective, the scenario context, the Round 1 task, Phase 2 — Board Options and the debrief questions. The Phase 1 group data is in the facilitator file only: distribute it separately to each group.',
      'Running the exercise:\n1. Allow 5 minutes for participants to read the scenario individually and silently.\n2. Assign each participant (or pair) a functional role — do not allow self-selection. Functional attachment to an assigned role is part of the learning.\n3. Run the group discussion for 10–12 minutes without facilitator intervention. Observe where dominant voices emerge, where functions dig in, and where the white space goes unaddressed.\n4. Stop the group before they reach consensus and ask: “Has anyone identified the white space yet — the gap between all your individual positions and the actual enterprise outcome?”',
      'Objective: To demonstrate how strategic distortion forms before decisions are made, and how collective intelligence must be deliberately structured to arrive at an integrated enterprise decision.',
      'Scenario Context. Company: Apex Manufacturing · Industry: Industrial Components.\nApex Manufacturing is a mid-sized industrial components company with a strong regional reputation. The board has placed pressure on the executive team to accelerate growth while maintaining financial stability and operational integrity. The executive team must determine the most appropriate strategic direction for the next 12–36 months.',
      'Key facilitation insight: The Distortion Lab is designed to produce bias-driven discussion even in a room full of people who have just spent hours learning about bias. This is intentional. Use it to demonstrate that structural design is what protects decision quality.') });
  await d.cards({ title: 'Phase 1 · Fragmented Reality', cols: 2, titleBeside: true, titleSize: 26, textSize: 24, iconSize: 0.6, items: [
    { icon: 'FaCoins', title: 'Group 1: Finance', text: 'Reality: Financial sustainability is under pressure.' },
    { icon: 'FaChartLine', title: 'Group 2: Market & Strategy', text: 'Reality: Growth acceleration is critical to remain competitive.' },
    { icon: 'FaIndustry', title: 'Group 3: Operations', text: 'Reality: Operational system is stretched and fragile.' },
    { icon: 'FaUsers', title: 'Group 4: People & Culture', text: 'Reality: Organisation may not absorb further strain.' }],
    notes: N(
      'PHASE 1 — FRAGMENTED REALITY (Distribute separately to each group)',
      'Each group receives only its own data (facilitator file: “Distribute separately to each group”).',
      'Group 1: Finance\n- Margins declining over last 2 years\n- Capital constraints tightening\n- Debt capacity limited\n- Large investments increase financial risk\nReality: Financial sustainability is under pressure.',
      'Group 2: Market & Strategy\n- Adjacent markets growing faster than core\n- Competitors expanding aggressively\n- Strong acquisition targets available\nReality: Growth acceleration is critical to remain competitive.',
      'Group 3: Operations\n- Plants near full capacity\n- Integration capability limited\n- Previous integration effort struggled\nReality: Operational system is stretched and fragile.',
      'Group 4: People & Culture\n- Leadership bandwidth constrained\n- Change fatigue visible\n- Talent retention becoming a concern\nReality: Organisation may not absorb further strain.',
      'Round 1 Task: Each group defines a strategic direction based only on their data. Prepare: one strategic recommendation and key rationale.') });
  await d.cards({ title: 'Phase 2 · Board Options', cols: 3, titleSize: 28, textSize: 24, items: [
    { icon: 'FaSeedling', title: 'A · Organic Growth', text: '$40M capacity expansion · 18–22% growth' },
    { icon: 'FaHandshake', title: 'B · Acquisition', text: '$65M · 35–45% growth · 40% of similar deals underperform' },
    { icon: 'FaPauseCircle', title: 'C · Strategic Pause', text: 'No major capital investment for 18 months' }],
    band: 'Define ONE integrated enterprise decision.',
    notes: N(
      'PHASE 2 — BOARD OPTIONS (Reveal ONLY after Round 1 is complete)',
      'Ask participants to mark their choice before revealing others.',
      'Option A · Organic Growth: Invest $40M in capacity expansion. Projected revenue growth: 18–22%. Risk: Moderate.\nOption B · Acquisition: Acquire competitor in adjacent market. Investment: $65M. Projected revenue growth: 35–45%. 40% of similar acquisitions underperform. Risk: High Integration Complexity.\nOption C · Strategic Pause: No major capital investment for 18 months. Focus on capability building and market intelligence. Risk: Competitive Displacement Risk.',
      'The Task: Given everything now visible — what is the right decision for the enterprise, and how do these options help or limit that decision. Define ONE integrated enterprise decision.\nConstraints: Must address growth · Must consider financial sustainability · Must reflect operational reality · Must consider people capacity.') });
  await d.list({ title: 'Distortion Lab · Debrief questions', fontSize: 28, rows: [
    { icon: 'FaClock', text: 'When did you form your preferred option?' },
    { icon: 'FaCompass', text: 'What shaped that preference?' },
    { icon: 'FaExchangeAlt', text: 'What changed after seeing all perspectives?' },
    { icon: 'FaPuzzlePiece', text: 'What made integration difficult?' }],
    notes: N(
      'DEBRIEF QUESTIONS',
      'Debrief after the simulation: Return to the three bias families most relevant to the scenario. Ask: “Which biases were operating in this room just now — and did knowing about them protect you from them?” The expected and honest answer is usually: not fully. That is the lesson.',
      'Ask each debrief question in turn:\n- When did you form your preferred option?\n- What shaped that preference?\n- What changed after seeing all perspectives?\n- What made integration difficult?',
      'Content: From Fragmented Thinking to Collective Intelligence — leaders typically form a strategic position before options are formally presented. This demonstrates how bias shapes decision-making early in the process. Collective intelligence requires deliberate integration of partial realities.\nThe quality of strategy execution is a function of the quality of the thinking environment.',
      'Transition: move to Section 6.1 · The Five Commitments.') });
  await d.list({ title: '6.1 · The Five Commitments', fontSize: 26, rows: [
    { icon: 'FaBrain', label: 'C1', text: 'I Know My Biases' },
    { icon: 'FaThermometerHalf', label: 'C2', text: 'I Manage My Emotional Impact' },
    { icon: 'FaShieldAlt', label: 'C3', text: 'I Build Psychological Safety Deliberately' },
    { icon: 'FaCogs', label: 'C4', text: 'I Use Process to Protect Quality' },
    { icon: 'FaUsers', label: 'C5', text: 'I Treat People as the Strategy' }],
    notes: N(
      '6.1 · THE FIVE COMMITMENTS: SELF-SCORING ASSESSMENT\nTime: 15–18 minutes including scoring and debrief (this slide and the next).',
      'Setting up the assessment. Before participants begin scoring, read the instruction aloud: “Score what is consistently true of your practice right now. The value of this tool is entirely dependent on your honesty.” Allow silence to settle before they begin.',
      'Participant activity (participant file, Section 6.1): individually and in silence, participants work through each commitment tab (C1 through C5) and score themselves 1–5 on each statement, then click Results. Allow 10–12 minutes for completion without interruption.\nScale: 1 = Rarely/never · 2 = Occasionally · 3 = Sometimes · 4 = Often · 5 = Consistently. Twenty statements, four per commitment; each commitment totals out of 20; overall score out of 100.',
      'C1 · I Know My Biases — I actively work to identify the patterns in my thinking that may not serve the organisation’s interests — particularly in the areas of overconfidence, confirmation, and status quo bias.\n1. When I receive information that confirms my existing view of a situation, I actively look for what it might be missing, overstating, or leaving out.\n2. I can name two or three specific patterns in my own thinking that have led me toward a poor call or a missed signal — and I actively watch for them.\n3. When something I championed does not go as expected, I examine what in my reasoning contributed to it.\n4. I regularly and deliberately seek out perspectives that challenge how I am reading a situation, particularly from people who are likely to see it differently from me.',
      'C2 · I Manage My Emotional Impact — I recognise that my emotional state — visible or not — sets the climate for how those around me think, speak up, and engage. I take responsibility for that climate.\n1. I am aware, in real time, of how my visible enthusiasm, scepticism, or frustration shapes what others feel able to say or contribute in the room.\n2. When I feel strongly that a particular direction or course of action is right, I consciously moderate how I signal that — to preserve the space for others to form and express their own views.\n3. I notice when those around me appear to be calibrating what they say to match what they think I want to hear, and I take deliberate steps to open that space back up.\n4. I can point to a recent moment where I visibly reconsidered my position based on input from someone with less authority or experience than me.',
      'C3 · I Build Psychological Safety Deliberately — I create the conditions in which honest, constructive challenge is expected and protected. I am the first to be challenged and the last to shut challenge down.\n1. The people I lead know — from observable evidence — that they can push back on a view I have taken publicly without personal or professional risk.\n2. In conversations I lead, I actively and specifically invite challenge and dissenting views before anyone volunteers them.\n3. When someone challenges my thinking, my first visible response is to engage with what they have raised.\n4. I recognise and acknowledge intellectual honesty — including views that are inconvenient or that cut against the prevailing direction — at least as visibly as I recognise agreement.',
      'C4 · I Use Process to Protect Quality — I do not rely on my own judgement alone. I use structured approaches to counteract the predictable failures of unassisted human reasoning.\n1. Before committing to a significant course of action, I use at least one deliberate, structured approach to pressure-test my thinking alongside instinct and experience.\n2. I actively look for relevant precedents or comparable situations that can help calibrate my assumptions before I commit to a direction.\n3. I separate the work of opening up possibilities from the work of narrowing down and committing — to reduce the risk of settling prematurely on a preferred path.\n4. I can recall a specific moment where a structured or deliberately designed thinking process led me to a different conclusion than my initial instinct would have.',
      'C5 · I Treat People as the Strategy — I invest in the human quality of my team’s thinking as well as in frameworks and data. I know that the best process produces the best outcome.\n1. I invest deliberate attention in how the people I lead think and engage with each other, as well as in the quality of what they produce.\n2. I design conversations and working sessions to draw out the best available thinking in the room before a direction forms.\n3. I treat the diversity of experience, background, and perspective in my team as something that actively improves the quality of what we arrive at together.\n4. I can point to evidence that the way my team thinks and works together produces better outcomes than individual expertise or data alone would.') });
  await d.list({ title: '6.1 · Score interpretation', fontSize: 26, rows: [
    { icon: 'FaTrophy', label: '85–100', text: 'Leading Practice' },
    { icon: 'FaCheckCircle', label: '65–84', text: 'Established Awareness' },
    { icon: 'FaSeedling', label: '45–64', text: 'Developing Awareness' },
    { icon: 'FaSun', label: '25–44', text: 'Emerging Awareness' },
    { icon: 'FaExclamationTriangle', gold: true, label: '20–24', text: 'At Risk' }],
    notes: N(
      '6.1 · VIEWING RESULTS AND DEBRIEF',
      'After the assessment: participants open their Results and read the interpretation for their level before any discussion begins.',
      'Watch for (facilitation caution): Do not ask participants to share their overall score publicly. Invite them to share only what they are comfortable sharing. The assessment is a personal diagnostic. Reinforce this explicitly before the debrief.',
      'Group debrief — three questions:\n1. “What did your score reveal that surprised you?”\n2. “Which single commitment had the lowest sub-score — and what does that tell you?”\n3. “What is one concrete action you will take before your next strategy session based on what this assessment surfaced?”',
      'Score interpretation:\n85–100 · Leading Practice: Your self-assessment suggests a high and consistent level of behavioural awareness in your leadership practice. You are operating with genuine insight into your own thinking patterns, creating the conditions for honest challenge, and protecting the quality of your judgement through deliberate process. At this level the priority shifts from building the practice to sustaining it under pressure — and extending it to the people and environments around you. Consider whether what you have built depends on your presence, or whether it is becoming embedded in how those you lead think and work.\n65–84 · Established Awareness: You have developed meaningful behavioural competence and it is visible in your day-to-day leadership. There are areas of genuine strength alongside areas where consistency may vary — particularly when conditions are pressured, ambiguous, or moving fast. Review your per-commitment scores to identify where your practice holds most reliably and where it is most dependent on circumstances being favourable. The transition from established to leading typically requires active focus on the commitments that feel least natural.\n45–64 · Developing Awareness: You have clear awareness of these commitments and an emerging practice — but gaps exist between what you know and what you do with consistency. This is a common and productive stage: the understanding is in place; the habits are still forming. Focus initially on one or two commitments where the gap between aspiration and practice feels smallest, and build from there. Behavioural leadership literacy develops through repeated, intentional application in real moments where the stakes are present.\n25–44 · Emerging Awareness: Your score suggests that while some awareness of these commitments exists, systematic practice is not yet in place across most of them. Leaders at this level often understand what good looks like but have not yet created the conditions — in their own habits, their team culture, or their working processes — that translate awareness into discipline. Identify the commitment where your score is lowest: this is likely where your leadership is most exposed and where focused attention will have the greatest impact.\n20–24 · At Risk: A score at this level suggests that the quality of thinking and judgement in your leadership environment may be significantly exposed to unmanaged cognitive and social bias. This signals that the practices, conditions, and structures required to protect that quality are not yet in place. Treat this as a priority finding. The costs of unmanaged bias in leadership — in poor calls, missed signals, and eroded trust — tend to accumulate gradually in ways that are difficult to trace until they become expensive to reverse.',
      'A final note. Self-assessment is the beginning of the work. The most useful thing you can do with this tool is to share what it surfaced with someone who observes you closely, and to let that become a real conversation.') });
  await d.cards({ title: 'Portfolio Artefact', cols: 3, items: [
    { icon: 'FaPenFancy', title: 'What has shifted', text: 'Reference a bias family, a phase of strategy and an emotional climate concept.' },
    { icon: 'FaFlagCheckered', title: 'Commitment to Action', text: 'One observable change in the next 30 days.' },
    { icon: 'FaBullseye', title: 'Your Development Priority', text: 'Your most exposed commitment, and what growth looks like for you.' }],
    notes: N(
      'UNIT CLOSING REFLECTION — PORTFOLIO ARTEFACT (participant file: “Your Learning in Your Own Words”)',
      'Participant activity (participant file, Section 6): This is your unit closing piece — a portfolio artefact that captures your learning from across the foundation unit and commits you to a direction of development.',
      'Part 1: What has shifted in how you understand your own thinking and your organisation’s strategic decision-making? Be specific — reference at least one bias family, one phase of strategy, and one emotional climate concept from this unit.',
      'Part 2 · Commitment to Action: Name one specific, observable change you will make to how you lead, facilitate, or participate in strategy conversations in the next 30 days. What will be different, and how will you know it has worked?',
      'Part 3 · Your Development Priority: Based on your Five Commitments assessment score, what is the single commitment where you are most exposed? What does genuine growth in that commitment look like for you specifically?',
      'Participants click Save Portfolio Artefact, then submit Unit 1 to the facilitator from their file (supporting documents can be attached: PDF, Word, Excel, PowerPoint, PNG, JPG; 20 MB per file, 5 files per submission).') });
  await d.prompt({ icon: 'FaRedo', label: 'Unit Summary · Return to the opening question', text: 'What assumption did you hold about how good decisions get made in your organisation? Has anything shifted?',
    foot: 'The one thing I am taking from this unit that I intend to act on is…',
    notes: N(
      'UNIT SUMMARY · UNIT 1 SYNTHESIS',
      'Closing the unit: Read the summary aloud or ask a participant to read it. The summary is intentionally compact — it is designed to crystallise the arc of the unit in under two minutes. Do not add to it. Let it do its work.',
      'Unit Summary (facilitator file):\nUnit 1: Behavioural Strategy Fundamentals establishes the psychological bedrock that underpins all strategic decision-making.\nIt opens by defining behavioural strategy as the intersection of cognitive psychology and strategic management — making the case that strategy is a deeply human exercise shaped by invisible mental filters. The unit introduces Kahneman’s dual-process framework (System 1 fast thinking vs. System 2 deliberate thinking) as the core framework through which leaders should understand their own judgement.\nFrom there, it maps 20 cognitive biases across four families — Action-Oriented, Stability, Interest, and Social — showing how each distorts strategic decisions in predictable, measurable ways, and what the organisational warning signs look like in practice.\nThe unit then traces where these biases show up across the four phases of any strategy process: Diagnosis, Option Generation, Decision, and Execution — demonstrating that bias is a process vulnerability. It adds a second dimension through the emotional climate, showing how fear, ego, or grounded confidence in a leadership environment either amplifies or dampens the quality of thinking.\nIt closes with practical intervention — six debiasing principles, three pillars for building collective intelligence, and institutional practices for embedding behavioural discipline — culminating in a simulation exercise and a self-scoring leadership assessment across five commitments.\nThe central argument of the unit, in one line: the quality of your strategy is a direct function of the quality of the thinking environment in which it was made.',
      'Return to the opening question: “What assumption did you hold about how good decisions get made in your organisation?” Ask 2–3 participants: “Has anything shifted — and if so, what specifically?”',
      'Closing the room: Ask each participant to complete this sentence privately in writing: “The one thing I am taking from this unit that I intend to act on is…” Invite 2–3 to share voluntarily. This is the unit’s final anchoring moment.',
      'Transition to Module 2: Direct participants to the “Unit 1 Complete” button. Remind them that Module 2 — Direction — builds directly on the foundation established here. The behavioural awareness developed in Unit 1 is the filter through which all subsequent strategy work should pass.') });

  await d.save(OUT); console.log('saved');
})().catch(e => { console.error(e); process.exit(1); });
